---
permalink: online-help-96-97/concept_flash_pool_statistics.html 
sidebar: sidebar 
keywords: flash, pool, statistics, system, manager, ssd, tier, read, write, workload, aggregate, online, help 
summary: Mit System Manager können Sie die Lese- und Schreib-Workloads der SSD-Ebene in Echtzeit für ein ausgewähltes Flash Pool Aggregat anzeigen. 
---
= Zeigen Sie Flash Pool Statistiken mit System Manager - ONTAP 9.7 und früher an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie die Lese- und Schreib-Workloads der Echtzeit-SSD-Tier für ein ausgewähltes Flash Pool Aggregat anzeigen.



== Fenster „Statistiken für Flash Pool Aggregate“

Sie können die Lese- und Schreib-Workloads der SSD-Ebene in Echtzeit für ein ausgewähltes Flash Pool Aggregat anzeigen.

Diese Seite ist nicht für ein Cluster verfügbar, das Nodes mit All-Flash-optimiertem Charakter enthält.

* *Anzeige von Statistiken für Flash Pool Aggregat*
+
Aus der Liste der Flash Pool Aggregate können Sie das Flash Pool Aggregat auswählen, dessen Statistiken Sie anzeigen möchten.





=== SSD-Cache-Workload für Lesevorgänge

Zeigt eine grafische Ansicht der gesamten Leseanforderungen an das Flash Pool Aggregat im Vergleich zu den vom SSD-Tier durchgeführten Leseoperationen an.



=== SSD-Cache-Workload für Schreibvorgänge

Zeigt eine grafische Ansicht der Schreibanforderungen an das Flash Pool Aggregat im Vergleich zu den vom SSD-Tier durchgeführten Schreibvorgängen an.
