---
permalink: online-help-96-97/concept_ipspaces.html 
sidebar: sidebar 
keywords: ipspace, edit,rename, system, manager, manage, online, help 
summary: Sie können mit System Manager IPspaces erstellen und verwalten. 
---
= Managen Sie IPspaces mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) zum Erstellen und Verwalten von IPspaces verwenden.



== IPspaces bearbeiten

Sie können mit System Manager einen vorhandenen IPspace umbenennen.

.Über diese Aufgabe
* Alle IPspace-Namen müssen innerhalb eines Clusters eindeutig sein und dürfen nicht aus Namen bestehen, die vom System reserviert sind, z. B. lokaler oder localhost.
* Der vom System definierte IPspace „`Default`“ und der IPspace „`Cluster`“ können nicht geändert werden.


.Schritte
. Klicken Sie auf *Netzwerk* > *IPspaces*.
. Wählen Sie den IPspace aus, den Sie ändern möchten, und klicken Sie dann auf *Bearbeiten*.
. Geben Sie im Dialogfeld *IPspace bearbeiten* einen neuen Namen für den IPspace an.
. Klicken Sie Auf *Umbenennen*.




== Löschen Sie IPspaces

Sie können mit System Manager einen IPspace löschen, wenn Sie den IPspace nicht mehr benötigen.

.Bevor Sie beginnen
Der zu löschende IPspace darf nicht mit Broadcast-Domänen, Netzwerkschnittstellen, Peer-Beziehungen oder Storage Virtual Machines (SVMs) verknüpft werden.

.Über diese Aufgabe
Der vom System definierte IPspace „`Default`“ und der IPspace „`Cluster`“ können nicht gelöscht werden.

.Schritte
. Klicken Sie auf *Netzwerk* > *IPspaces*.
. Wählen Sie den IPspace aus, den Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Aktivieren Sie das Bestätigungsfeld, und klicken Sie dann auf *Ja*.


*Verwandte Informationen*

https://docs.netapp.com/us-en/ontap/networking/index.html["Netzwerkmanagement"]
