---
permalink: online-help-96-97/concept_svm_user_accounts.html 
sidebar: sidebar 
keywords: system, manager, create, manage, online, help, storage, virtual, machine, svm, user, account, password, change, lock, unlock , command, button 
summary: 'Mit System Manager können Sie Benutzerkonten für Storage Virtual Machines (SVM) erstellen und managen.' 
---
= Erstellen und Managen der SVM-Benutzerkonten mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie Benutzerkonten für Storage Virtual Machines (SVM) erstellen und managen.



== Fügen Sie SVM-Benutzerkonten hinzu

Mit System Manager können Sie ein SVM-Benutzerkonto (Storage Virtual Machine) hinzufügen und eine Anmeldemethode für den Zugriff auf das Storage-System festlegen.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fenster *SVM User Details* auf *Users*.
. Klicken Sie Auf *Hinzufügen*.
. Geben Sie einen Benutzernamen und ein Kennwort für die Verbindung zum Speichersystem an, und bestätigen Sie das Passwort.
. Fügen Sie eine oder mehrere Anmeldemethoden für Benutzer hinzu und klicken Sie dann auf *Hinzufügen*.
+
Eine Anmeldemethode für das neue vsadmin-Konto ist automatisch enthalten, die HTTP als Anwendung verwendet und mit einem Zertifikat authentifiziert wird.





== Passwort für SVM-Benutzerkonten ändern

Sie können mit System Manager das Passwort für ein SVM-Benutzerkonto (Storage Virtual Machine) zurücksetzen.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fenster *SVM User Details* auf *Users*.
. Wählen Sie das Benutzerkonto aus, für das Sie das Passwort ändern möchten, und klicken Sie dann auf *Passwort zurücksetzen*.
. Geben Sie im Dialogfeld *Passwort zurücksetzen* das neue Passwort ein, bestätigen Sie das neue Passwort und klicken Sie dann auf *Ändern*.




== SVM-Benutzerkonten bearbeiten

Mit System Manager können Sie ein SVM-Benutzerkonto (Storage Virtual Machine) bearbeiten, indem Sie die Anmeldemethoden für den Zugriff auf das Storage-System ändern.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fenster *SVM User Details* auf *Users*.
. Wählen Sie das Benutzerkonto aus, das Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Ändern Sie eine oder mehrere Anmeldemethoden für Benutzer und klicken Sie dann auf *Ändern*.




== SVM-Benutzerkonten sperren oder entsperren

Mit System Manager können Benutzerkonten für Storage Virtual Machines (SVM) gesperrt oder entsperrt werden.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fenster *SVM User Details* auf *Users*.
. Wählen Sie im Fenster *Benutzer* das Benutzerkonto aus, für das Sie den Kontostatus ändern möchten, und klicken Sie dann nach Bedarf entweder auf *gesperrt* oder *entsperren*.




== Fenster „Benutzer“

Sie können das Fenster Benutzer verwenden, um Benutzerkonten zu verwalten, das Kennwort eines Benutzers zurückzusetzen und Informationen über alle Benutzerkonten anzuzeigen.



=== Befehlsschaltflächen

* *Hinzufügen*
+
Öffnet das Dialogfeld Benutzer hinzufügen, in dem Sie Benutzerkonten hinzufügen können.

* *Bearbeiten*
+
Öffnet das Dialogfeld Benutzer ändern, in dem Sie Benutzeranmeldungsmethoden ändern können.

+
[NOTE]
====
Als Best Practice empfiehlt es sich, für alle Zugriffs- und Authentifizierungsmethoden eines Benutzerkontos eine einzelne Rolle zu verwenden.

====
* *Löschen*
+
Ermöglicht das Löschen eines ausgewählten Benutzerkontos.

* *Passwort Ändern*
+
Öffnet das Dialogfeld Kennwort ändern, in dem Sie das Kennwort eines ausgewählten Benutzers zurücksetzen können.

* *Schloss*
+
Sperrt das Benutzerkonto.

* *Aktualisieren*
+
Aktualisiert die Informationen im Fenster.





=== Benutzerliste

Im Bereich unterhalb der Liste Benutzer werden detaillierte Informationen zum ausgewählten Benutzer angezeigt.

* * Benutzer*
+
Zeigt den Namen des Benutzerkontos an.

* *Konto Gesperrt*
+
Zeigt an, ob das Benutzerkonto gesperrt ist.





=== Bereich Anmeldemethoden für Benutzer

* * Anwendung*
+
Zeigt die Zugriffsmethode an, mit der ein Benutzer auf das Speichersystem zugreifen kann. Zu den unterstützten Zugriffsmethoden gehören folgende:

+
** Systemkonsole (Konsole)
** HTTP(S) (http)
** ONTAP-API (ontapi)
** Service-Prozessor (Service-Prozessor)
** SSH (SSH)


* *Authentifizierung*
+
Zeigt die standardmäßig unterstützte Authentifizierungsmethode an, die „`password`“ ist.

* * Rolle*
+
Zeigt die Rolle eines ausgewählten Benutzers an.


