---
permalink: online-help-96-97/concept_what_compatible_spare_disks_are.html 
sidebar: sidebar 
keywords: system, manager, compatible, spare, disk, hdd, compacity, raid, online, help 
summary: 'In System Manager sind kompatible Spare-Festplatten Festplatten, die mit den Eigenschaften anderer Festplatten im Aggregat übereinstimmen. Wenn Sie die Größe eines vorhandenen Aggregats durch Hinzufügen von HDDs (Kapazitätsfestplatten) oder Änderung des RAID-Typs eines Aggregats von RAID4 auf RAID-DP erhöhen möchten, muss das Aggregat ausreichend kompatible freie Festplatten enthalten.' 
---
= Kompatible Spare-Festplatten in System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) sind kompatible Ersatzfestplatten, die zu den Eigenschaften anderer Festplatten im Aggregat passen. Wenn Sie die Größe eines vorhandenen Aggregats durch Hinzufügen von HDDs (Kapazitätsfestplatten) oder Änderung des RAID-Typs eines Aggregats von RAID4 auf RAID-DP erhöhen möchten, muss das Aggregat ausreichend kompatible freie Festplatten enthalten.

Eigenschaften von Festplatten, die mit dem Festplattentyp übereinstimmen müssen, die Festplattengröße (kann eine höhere Festplattengröße sein, falls dieselbe Festplattengröße nicht verfügbar ist), Festplatten-RPM, Prüfsumme, Node-Eigentümer, Pool, Und Eigenschaften von freigegebenen Datenträgern. Wenn Sie größere Festplatten verwenden, müssen Sie beachten, dass Festplattenabbau auftreten und die Größe aller Festplatten auf die geringste Festplattenkapazität reduziert wird. Vorhandene gemeinsam genutzte Festplatten werden mit einer höheren Größe nicht gemeinsam genutzter Festplatten abgeglichen und die nicht freigegebenen Festplatten werden in freigegebene Festplatten umgewandelt und als Spares hinzugefügt.

Wenn eine Kombination von RAID-Optionen, wie zum Beispiel die Kombination von Festplattentypen und Festplatten-U/min, für die RAID-Gruppe aktiviert ist, Der Festplattentyp und die Festplatten-RPM der vorhandenen Festplatten des Aggregats werden dem effektiven Festplattentyp und den effektiven Festplatten-RPM der Spare-Festplatten zugeordnet, um kompatible Spares zu erhalten.

*Verwandte Informationen*

xref:task_adding_capacity_disks.adoc[Hinzufügen von Kapazitätsfestplatten]

xref:task_editing_aggregates.adoc[Bearbeitung von Aggregaten]
