---
permalink: online-help-96-97/concept_cluster_expansion.html 
sidebar: sidebar 
keywords: cluster, expanision, system, manager, storage, size, capabilities, add, node, configure, network, online, help 
summary: Mit System Manager können Sie die Größe und den Funktionsumfang Ihres Storage erhöhen, indem Sie dem Cluster kompatible Nodes hinzufügen und die Node-Netzwerkdetails konfigurieren. Sie können auch die Zusammenfassung der Nodes anzeigen. 
---
= Cluster-Erweiterung mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und älter) können Sie die Größe und den Funktionsumfang Ihres Storage erhöhen, indem Sie dem Cluster kompatible Nodes hinzufügen und Details zum Node-Netzwerk konfigurieren. Sie können auch die Zusammenfassung der Nodes anzeigen.

Wenn Sie sich bei System Manager anmelden, erkennt der System Manager automatisch kompatible Nodes, die verkabelt, dem Cluster jedoch nicht hinzugefügt wurden, und fordert Sie zum Hinzufügen der Nodes auf. Sie können kompatible Nodes so und hinzufügen, wenn System Manager die Nodes erkannt hat. Oder Sie können die Nodes zu einem späteren Zeitpunkt manuell hinzufügen.



== Fügen Sie Nodes zu einem Cluster hinzu

Mit System Manager können Sie die Größe und den Funktionsumfang Ihres Storage-Systems erhöhen, indem Sie einem vorhandenen Cluster Nodes hinzufügen.

.Bevor Sie beginnen
* Neue kompatible Nodes müssen mit dem Cluster verbunden werden.
+
Im Fenster Netzwerk werden nur die Ports aufgeführt, die sich in der Standard-Broadcast-Domäne befinden.

* Alle Nodes im Cluster müssen betriebsbereit sein.
* Alle Nodes müssen dieselbe Version aufweisen.


.Schritte
. Fügen Sie die neuen kompatiblen Nodes dem Cluster hinzu:
+
|===
| Ihr Unternehmen | Tun Sie das... 


 a| 
Nicht bei System Manager angemeldet
 a| 
.. Melden Sie sich bei System Manager an.
+
[NOTE]
====
Die neuen kompatiblen Nodes werden von System Manager bei der Anmeldung automatisch erkannt. Sie werden von System Manager aufgefordert, die neuen kompatiblen Nodes zum Cluster hinzuzufügen.

====
.. Klicken Sie auf *Knoten zu Cluster hinzufügen*.
.. Ändern Sie den Namen der Nodes.
.. Geben Sie die Knotenlizenzen an.
.. Klicken Sie auf *Absenden und fortfahren*.




 a| 
Bei System Manager angemeldet
 a| 
.. Klicken Sie Auf *Konfiguration* > *Cluster* > *Erweiterung*.
+
System Manager sucht nach neu hinzugefügten Nodes. Wenn Warnungen angezeigt werden, müssen Sie sie beheben, bevor Sie fortfahren. Wenn neue kompatible Nodes erkannt werden, fahren Sie mit dem nächsten Schritt fort.

.. Ändern Sie den Namen der Nodes.
.. Geben Sie die Knotenlizenzen an.
.. Klicken Sie auf *Absenden und fortfahren*.


|===




== Konfigurieren Sie die Netzwerkdetails der Nodes

Mit System Manager können Sie die LIF- und Service-Prozessor-Einstellungen für das Node-Management für die neu hinzugefügten Nodes konfigurieren.

.Bevor Sie beginnen
* Im Standard-IPspace muss für die LIF-Erstellung eine ausreichende Anzahl von Ports vorhanden sein.
* Alle Ports müssen betriebsbereit sein und ausgeführt werden.


.Schritte
. Konfiguration des Node-Managements:
+
.. Geben Sie die IP-Adresse in das Feld * IP-Adresse* ein.
.. Wählen Sie den Port für die Knotenverwaltung im Feld *Port* aus.
.. Geben Sie die Netzmaske und Gateway-Details ein.


. Konfigurieren Sie die Service Processor-Einstellungen:
+
.. Aktivieren Sie das Kontrollkästchen *Standardeinstellungen überschreiben*, um die Standardwerte zu überschreiben.
.. Geben Sie IP-Adresse, Netmask und Gateway-Details ein.


. Klicken Sie auf *Senden und Fortfahren*, um die Netzwerkkonfiguration der Knoten abzuschließen.
. Überprüfen Sie die Details der Knoten auf der Seite *Zusammenfassung*.




=== Nächste Schritte

* Wenn Ihr Cluster geschützt ist, sollten Sie die erforderliche Anzahl von Intercluster LIFs in den neu hinzugefügten Nodes erstellen, um TeilPeering und einen ungesunden Schutz zu vermeiden.
* Wenn SAN-Datenprotokolle in Ihrem Cluster aktiviert sind, sollten Sie die erforderliche Anzahl an SAN-Daten-LIFs für die Datenbereitstellung erstellen.


*Verwandte Informationen*

xref:task_creating_network_interfaces.adoc[Erstellen von Netzwerkschnittstellen]
