---
permalink: online-help-96-97/concept_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policy, system, manager, create, edit, delete, online, help, flexvol, window 
summary: Mit System Manager können Sie Effizienzrichtlinien erstellen, bearbeiten und löschen. 
---
= Management von Effizienzrichtlinien mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP System Manager Classic (verfügbar in ONTAP 9.7 und früher) verwenden, um Richtlinien für die Effizienz zu erstellen, zu bearbeiten und zu löschen.



== Hinzufügen von Effizienzrichtlinien

Mithilfe von System Manager lassen sich die Effizienzrichtlinien zur Ausführung der Deduplizierung auf einem Volume zu einem bestimmten Zeitplan hinzufügen oder wenn die Änderung der Volume-Daten einen bestimmten Schwellwert erreicht.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *Effizienzrichtlinien*.
. Klicken Sie auf *Hinzufügen* und geben Sie dann den Namen der Richtlinie an.
. Legen Sie fest, wie die Storage-Effizienz-Richtlinie ausgeführt werden soll:
+
** Wählen Sie *Zeitplan*, und geben Sie den Terminplannamen und die Terminplandetails an.
+
Sie können bei Bedarf die maximale Laufzeit der Effizienzrichtlinie angeben.

** Wählen Sie *Änderungsschwellenwert* und geben Sie den Schwellenwert (in Prozent) für die Änderung der Volumendaten an.


. *Optional:* Aktivieren Sie das Kontrollkästchen *QoS-Richtlinie auf Hintergrund setzen*, um die Auswirkungen auf die Leistung auf den Client-Betrieb zu verringern.
. Klicken Sie Auf *Hinzufügen*.




== Bearbeiten von Effizienzrichtlinien

Mit System Manager können Sie die Attribute einer Effizienzrichtlinie ändern, z. B. Richtlinienname, Planungsname und maximale Laufzeit.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *Effizienzrichtlinien*.
. Wählen Sie im Fenster *Effizienzrichtlinien* die Richtlinie aus, die Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Nehmen Sie im Dialogfeld *Effizienzrichtlinie bearbeiten* die erforderlichen Änderungen vor.
. Klicken Sie Auf *Speichern*.




== Effizienzrichtlinien löschen

Sie können System Managerto eine nicht mehr erforderliche Effizienzrichtlinie löschen.

.Bevor Sie beginnen
Die Effizienzrichtlinie muss deaktiviert werden.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *Effizienzrichtlinien*.
. Wählen Sie die Effizienzrichtlinie aus, die Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Aktivieren Sie das Bestätigungsfeld, und klicken Sie dann auf *Löschen*.




== Aktivieren oder Deaktivieren von Effizienzrichtlinien

Mit System Manager können Sie eine Effizienzrichtlinie aktivieren oder deaktivieren.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *Effizienzrichtlinien*.
. Wählen Sie eine oder mehrere Effizienzrichtlinien aus, die aktiviert bzw. deaktiviert werden sollen.
. Klicken Sie bei Bedarf auf *Status* > *Aktivieren* oder *Status* > *Deaktivieren*.
. Wenn Sie eine Effizienzrichtlinie deaktivieren, aktivieren Sie das Bestätigungsfeld und klicken Sie dann auf *OK*.




== Was für eine Effizienzrichtlinie ist

Eine Effizienzrichtlinie ist ein Aufgabenplan für einen Deduplizierungsvorgang auf einem FlexVol Volume.

Sie können die Deduplizierung auf einem FlexVol Volume ausführen, indem Sie die Vorgänge zu einem bestimmten Zeitpunkt planen oder angeben, dass diese bei einem Überschreitung eines Schwellenwerts ausgelöst werden. Sie können einen Deduplizierungsvorgang planen, indem Job-Zeitpläne erstellt werden, die innerhalb der Effizienzrichtlinien eingeschlossen sind. Die Volume-Effizienzrichtlinien unterstützen nur Job-Zeitpläne, die vom Typ Cron sind. Alternativ können Sie einen Schwellenwert in Prozent angeben. Wenn neue Daten den angegebenen Prozentsatz überschreiten, wird der Deduplizierungsvorgang gestartet.



== Allgemeines zu vordefinierten Effizienzrichtlinien

Sie können ein Volume mit Effizienzrichtlinien konfigurieren, um zusätzliche Platzeinsparungen zu erzielen. Sie können ein Volume so konfigurieren, dass die Inline-Komprimierung ausgeführt wird, ohne dass ein auf dem Volume konfigurierter Hintergrundeffizienzvorgang geplant oder manuell gestartet wird.

Wenn Sie eine SVM erstellen, werden die folgenden Effizienzrichtlinien automatisch erstellt und können nicht gelöscht werden:

* Standard
+
Sie können ein Volume mithilfe der Effizienzrichtlinie konfigurieren, um die geplanten Deduplizierungsvorgänge auf dem Volume auszuführen.

* Nur Inline
+
Sie können ein Volume mit der reinen Inline-Effizienzrichtlinie konfigurieren und die Inline-Komprimierung aktivieren, um eine Inline-Komprimierung auf dem Volume auszuführen. Dafür sind keine geplanten oder manuellen Vorgänge im Hintergrund erforderlich.



Weitere Informationen zu den reinen Inline-Richtlinien und zu den Standardrichtlinien für mehr Effizienz finden Sie in den man-Pages.



== Das Fenster „Effizienzrichtlinien“

Sie können im Fenster „Efficiency Policies“ Informationen zu Effizienzrichtlinien erstellen, anzeigen und managen.



=== Befehlsschaltflächen

* *Hinzufügen*
+
Öffnet das Dialogfeld „Add Efficiency Policy“, in dem Sie einen Deduplizierungsvorgang für einen bestimmten Zeitraum (planbasiert) auf einem Volume ausführen können oder wenn die Änderung der Volume-Daten einen bestimmten Schwellwert erreicht (schwellenwertbasiert).

* *Bearbeiten*
+
Öffnet das Dialogfeld „Edit Efficiency Policy“, das es Ihnen ermöglicht, den Zeitplan, den Schwellenwert, den QoS-Typ und die maximale Laufzeit für einen Deduplizierungsvorgang zu ändern.

* *Löschen*
+
Öffnet das Dialogfeld „Effizienzrichtlinie löschen“, in dem Sie die ausgewählte Effizienzrichtlinie löschen können.

* *Status*
+
Öffnen Sie ein Dropdown-Menü mit Optionen zum Aktivieren oder Deaktivieren der ausgewählten Effizienzrichtlinie.

* *Aktualisieren*
+
Aktualisiert die Informationen im Fenster.





=== Liste der Effizienzrichtlinien

* *Auto*
+
Gibt an, dass die Deduplizierung kontinuierlich im Hintergrund durchgeführt wird. Diese Richtlinie gilt für alle neu erstellten Volumes und für alle aktualisierten Volumes, die nicht manuell für die Deduplizierung im Hintergrund konfiguriert wurden. Wenn Sie die Richtlinie in „`default`“ oder eine andere Richtlinie ändern, ist die Richtlinie „`Auto`“ deaktiviert.

+
Wenn ein Volume sich von einem nicht-All Flash FAS System auf ein AFF System verschiebt, ist die Richtlinie „`Auto`“ standardmäßig auf dem Ziel-Node aktiviert. Wenn ein Volume von einem AFF Node zu einem nicht All Flash FAS Node verschoben wird, wird die „`Auto`“-Richtlinie auf dem Ziel-Node standardmäßig durch die Richtlinie „`inline-only`“ ersetzt.

* *Richtlinien*
+
Gibt den Namen einer Effizienzrichtlinie an.

* *Status*
+
Gibt den Status einer Effizienzrichtlinie an. Für den Status kann einer der folgenden Werte angezeigt werden:

+
** Aktiviert
+
Gibt an, dass die Effizienzrichtlinie einem Deduplizierungsvorgang zugewiesen werden kann.

** Deaktiviert
+
Gibt an, dass die Effizienzrichtlinie deaktiviert ist. Sie können die Richtlinie über das Dropdown-Menü „Status“ aktivieren und diese später einem Deduplizierungsvorgang zuweisen.



* *Run By*
+
Gibt an, ob die Storage-Effizienz-Richtlinie basierend auf einem Zeitplan oder auf einem Schwellwert (Änderungsprotokoll-Schwellenwert) ausgeführt wird.

* *QoS-Richtlinie*
+
Gibt den QoS-Typ für die Storage-Effizienzrichtlinie an. Für den QoS-Typ kann einer der folgenden Werte verwendet werden:

+
** Hintergrund
+
Gibt an, dass die QoS-Richtlinie im Hintergrund ausgeführt wird, was die potenziellen Auswirkungen auf die Performance von Client-Operationen reduziert.

** Optimal eingesetzt
+
Gibt an, dass die QoS-Richtlinie nur auf Best-Effort-Grundlage ausgeführt wird, mit der Sie die Auslastung der Systemressourcen maximieren können.



* *Maximale Laufzeit*
+
Gibt die maximale Laufzeit einer Effizienzrichtlinie an. Wenn dieser Wert nicht angegeben wird, wird die Effizienzrichtlinie ausgeführt, bis der Vorgang abgeschlossen ist.





=== Detailbereich

Im Bereich unterhalb der Liste „Effizienzrichtlinie“ werden zusätzliche Informationen über die ausgewählte Effizienzrichtlinie angezeigt, einschließlich des Planungsnamens und der Planungsdetails für eine planplanbasierte Richtlinie sowie des Schwellenwerts für eine schwellenwertbasierte Richtlinie.
