---
permalink: online-help-96-97/concept_configuration_update.html 
sidebar: sidebar 
keywords: configuration, update, system, manager, administration, detail, storage, virtual, machine, svm, online, help, window, tab, node, command, button 
summary: 'Mit System Manager können Sie die Administrationsdetails für Storage Virtual Machines (SVMs) konfigurieren.' 
---
= Konfigurations-Update für System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) lassen sich die Administrationsaufgaben von Storage Virtual Machines (SVMs) konfigurieren.



== Konfigurieren Sie die Administratoren-Details einer SVM

Mit System Manager können Sie die Administrationsdetails einer Storage Virtual Machine (SVM) schnell konfigurieren. Optional können Sie die Administration der SVM an SVM-Administratoren delegieren.

.Über diese Aufgabe
Als SVM-Administrator können Sie mit System Manager delegierte SVMs nicht managen. Sie können derSVMsonly über die Befehlszeilenschnittstelle (CLI) verwalten.

.Schritte
. Klicken Sie Auf *Konfiguration* > *Cluster* > *Konfigurationsupdates*.
. Wählen Sie auf der Registerkarte *SVMs* den Knoten aus und klicken Sie dann auf *Administratordetails konfigurieren*.
. Richten Sie im Abschnitt *Administratordetails* ein Passwort für den ein `vsadmin` Benutzerkonto.
. Wenn Sie eine dedizierte LIF für SVM-Verwaltung benötigen, wählen Sie *Erstellen einer logischen Schnittstelle für SVM-Management* aus, und geben Sie dann die Netzwerkdetails an.
+
Für SAN-Protokolle ist eine dedizierte SVM-Management-LIF erforderlich, bei der Daten- und Managementprotokolle nicht dieselbe LIF teilen können. Das SVM-Management LIFs können nur auf Daten-Ports erstellt werden.

. Geben Sie Netzwerkdetails an:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Geben Sie die IP-Adresse mithilfe eines Subnetzes an
 a| 
.. Wählen Sie *mit einem Subnetz* aus.
.. Wählen Sie im Dialogfeld Details hinzufügen das Subnetz aus, dem die IP-Adresse zugewiesen werden muss.
+
Für Intercluster-LIFs werden nur die Subnetze angezeigt, die dem ausgewählten IPspace zugeordnet sind.

.. Wenn Sie der Schnittstelle eine bestimmte IP-Adresse zuweisen möchten, wählen Sie *eine bestimmte IP-Adresse verwenden* aus, und geben Sie dann die IP-Adresse ein.
+
Die IP-Adresse, die Sie angeben, wird dem Subnetz hinzugefügt, wenn diese IP-Adresse nicht bereits im Subnetz-Bereich vorhanden ist.

.. Klicken Sie auf *OK*.




 a| 
Geben Sie die IP-Adresse manuell an, ohne ein Subnetz zu verwenden
 a| 
.. Wählen Sie *ohne Subnetz*.
.. Führen Sie im Dialogfeld Details hinzufügen die folgenden Schritte aus:
+
... Geben Sie die IP-Adresse und Netzwerkmaske oder das Präfix an.
... Optional: Geben Sie das Gateway an.
+
Das Zielfeld wird basierend auf der Familie der IP-Adresse mit dem Standardwert gefüllt.

... Wenn der Standardwert nicht verwendet werden soll, geben Sie einen neuen Zielwert an.
Wenn keine Route vorhanden ist, wird automatisch eine neue Route basierend auf dem Gateway und dem Ziel erstellt.


.. Klicken Sie auf *OK*.


|===
. Geben Sie einen Port an, um eine Daten-LIF zu erstellen:
+
.. Klicken Sie Auf *Durchsuchen*.
.. Wählen Sie im Dialogfeld *Netzwerkanschluss auswählen oder Adapter* einen Port aus, und klicken Sie dann auf *OK*.






== Fenster „Konfigurationsaktualisierungen“

Mit dem Fenster Konfigurationsupdates können Sie die Konfigurationsdetails für das Cluster, die Storage Virtual Machine (SVM) und die Nodes aktualisieren.



=== Registerkarten

* *Knoten*
+
Ermöglicht Ihnen das Konfigurieren von Details zum Node.

* *SVMs*
+
Ermöglicht die Konfiguration der Details der SVM.





=== Registerkarte Knoten



=== Befehlsschaltflächen

* *Knotenname Bearbeiten*
+
Öffnet das Dialogfeld Knotenname bearbeiten, in dem Sie den Namen des Knotens ändern können.

* *Erstellen Sie Knoten-Management-LIF*
+
Öffnet das Dialogfeld Node-Management-LIF erstellen, das Ihnen ermöglicht, eine Node-Management-LIF zum Verwalten eines bestimmten Node zu erstellen.

* *AutoSupport bearbeiten*
+
Öffnet das Dialogfeld AutoSupport-Einstellungen bearbeiten, in dem Sie eine E-Mail-Adresse angeben können, von der aus E-Mail-Benachrichtigungen gesendet werden, und mehrere E-Mail-Adressen der Hostnamen hinzufügen können.





=== Registerkarte „SVMs“



=== Befehlsschaltfläche

* *Administratordetails Konfigurieren*
+
Öffnet das Dialogfeld „Administratordetails konfigurieren“, in dem Sie die Administratordetails der SVM konfigurieren können.



*Verwandte Informationen*

xref:task_creating_cluster.adoc[Erstellen eines Clusters]

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[Einrichten eines Netzwerks, wenn ein IP-Adressbereich deaktiviert ist]
