---
permalink: online-help-96-97/concept_how_volume_guarantees_work_for_flexvol_volumes.html 
sidebar: sidebar 
keywords: volume, guarantee, work, flexvol, volume, space, preallocated, aggregate, online, help 
summary: 'Volume-Garantien (manchmal auch „Speicherplatzgarantien“ genannt) bestimmen, wie der Speicherplatz eines Volume aus seinem enthaltenden Aggregat zugewiesen wird – unabhängig davon, ob der Speicherplatz vorab für das Volume zugewiesen wird.' 
---
= Über die Volume-Garantien für FlexVol Volumes mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volume-Garantien für FlexVol Volumes mit System Manager classic festlegen (erhältlich in ONTAP 9.7 und früher). Volume-Garantien (manchmal auch „_space garanties_“ genannt) bestimmen, wie Speicherplatz für ein Volume dem zugehörigen Aggregat zugewiesen wird - unabhängig davon, ob der Speicherplatz vorab für das Volume zugewiesen wird.

Die Garantie ist ein Attribut des Volume.

Sie stellen die Garantie bei der Erstellung eines neuen Volume fest. Sie können auch die Garantie für ein vorhandenes Volume ändern, vorausgesetzt, dass genügend freier Speicherplatz vorhanden ist, um die neue Garantie zu übernehmen.

Dies können die verschiedenen Volume-Garantiearten sein `volume` (Der Standardtyp) oder `none`.

* Ein Garantietyp von `volume` Beim Erstellen des Volume weist im Aggregat für das gesamte Volume Speicherplatz zu, unabhängig davon, ob dieser Speicherplatz noch für Daten verwendet wird.
+
Der zugewiesene Speicherplatz kann nicht einem anderen Volume in diesem Aggregat bereitgestellt bzw. zugewiesen werden.

* Eine Garantie von `none` Weist Speicherplatz aus dem Aggregat nur so zu, wie es vom Volume benötigt wird.
+
Der von Volumes mit diesem Garantietyp verbrauchte Speicherplatz wächst mit, wenn Daten hinzugefügt werden, anstatt von der ursprünglichen Volume-Größe bestimmt zu werden. Dadurch könnte Platz nicht genutzt werden, wenn die Volume-Daten nicht auf diese Größe anwachsen. Der maximalen Größe eines Volumes mit Garantie von `none` Ist nicht begrenzt durch die Menge an freiem Speicherplatz in seinem Aggregat. Die Gesamtgröße aller Volumes, die einem Aggregat zugeordnet sind, kann den freien Speicherplatz des Aggregats übersteigen, obwohl die Menge an Speicherplatz, die tatsächlich verwendet werden kann, durch die Größe des Aggregats begrenzt wird.

+
Schreibvorgänge auf LUNs oder Dateien (einschließlich platzsparender LUNs und Dateien) in diesem Volume könnten fehlschlagen, wenn das zugehörige Aggregat nicht über genügend Speicherplatz für den Schreibvorgang verfügt.



Wenn Speicherplatz im Aggregat für A zugewiesen ist `volume` Garantie für ein vorhandenes Volume wird dieser Speicherplatz nicht mehr als frei im Aggregat betrachtet, selbst wenn das Volume diesen Speicherplatz noch nicht nutzt. Vorgänge, die freien Speicherplatz im Aggregat benötigen, z. B. die Erstellung von Aggregat-Snapshot-Kopien oder die Erstellung neuer Volumes im Aggregat, die die Ressourcen enthalten, können nur stattfinden, wenn in diesem Aggregat genügend freier Speicherplatz verfügbar ist. Hierzu wird nicht der Speicherplatz genutzt, der bereits einem anderen Volume zugewiesen ist.

Wenn der freie Speicherplatz in einem Aggregat erschöpft ist, werden nur Schreibvorgänge auf Volumes oder Dateien in diesem Aggregat mit vorab zugewiesenem Speicherplatz garantiert erfolgreich.

Garantien werden nur für Online-Volumen gewährt. Wenn Sie ein Volume offline schalten, ist ein zugewiesener, aber ungenutzter Speicherplatz für dieses Volume für andere Volumes im Aggregat verfügbar. Wenn Sie versuchen, das Volume wieder online zu bringen, wenn der verfügbare Platz im Aggregat nicht zur Verfügung steht, um seine Garantie zu erfüllen, bleibt es offline. Sie müssen das Volume online stellen. Dann wird die Garantie des Volumes deaktiviert.

*Verwandte Informationen*

http://www.netapp.com/us/media/tr-3965.pdf["Technischer Bericht 3965: NetApp Thin Provisioning Deployment and Implementation Data ONTAP 8.1 (7-Mode)"^]
