---
permalink: online-help-96-97/concept_how_to_determine_when_safe_to_remove_multi_disk_carrier.html 
sidebar: sidebar 
keywords: remove, multidisk, carrier, system, manager, storage, disruption, raid 
summary: Wenn Sie einen Laufwerksträger entfernen, bevor dieser sicher ist, kann dies dazu führen, dass eine oder mehrere RAID-Gruppen beeinträchtigt werden oder es möglicherweise sogar zu einer Storage-Unterbrechung kommt. Mit System Manager können Sie feststellen, wann ein Speicheranbieter mit mehreren Festplatten sicher entfernt werden kann. 
---
= Ermitteln Sie, wann es sicher ist, einen Multidisk-Träger mit System Manager - ONTAP 9.7 und früher zu entfernen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Laufwerksträger entfernen, bevor dieser sicher ist, kann dies dazu führen, dass eine oder mehrere RAID-Gruppen beeinträchtigt werden oder es möglicherweise sogar zu einer Storage-Unterbrechung kommt. Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie feststellen, wann ein Speicherträger mit mehreren Festplatten sicher entfernt werden kann.

Wenn ein Laufwerksträger ausgetauscht werden muss, müssen die folgenden Ereignisse aufgetreten sein, bevor Sie den Träger sicher entfernen können:

* Es muss eine AutoSupport-Meldung protokolliert werden, die angibt, dass der Spediteur zum Entfernen bereit ist.
* Es muss eine EMS-Nachricht protokolliert werden, die angibt, dass der Spediteur zum Entfernen bereit ist.
* Der Status beider Laufwerke im Träger muss als angezeigt werden `broken` Im Fenster Festplatten.
+
Sie müssen die Festplatten erst entfernen, nachdem der Trägerpartner einer ausgefallenen Festplatte evakuiert wurde. Sie können auf Details klicken, um den Status der Festplattenevakuierung auf der Registerkarte Eigenschaften des Fensters Festplatten anzuzeigen.

* Die Fehler-LED (gelb) am Träger muss ständig leuchten, was darauf hinweist, dass sie zum Ausbauen bereit ist.
* Die Aktivitäts-LED (grün) muss ausgeschaltet werden, damit keine Laufwerksaktivität erfolgt.
* In der digitalen Anzeige des Shelf wird nur die Shelf-ID-Nummer angezeigt.


[NOTE]
====
Sie können den Carrier-Mate einer ausgefallenen Festplatte nicht wiederverwenden. Wenn Sie einen Träger mit mehreren Festplatten entfernen, der ein ausgefallenes Laufwerk enthält, müssen Sie es durch einen neuen Datenträger ersetzen.

====