---
permalink: online-help-96-97/concept_nfs_protocol.html 
sidebar: sidebar 
keywords: nfs, protocol, system, manager, authenticate, client, asses, data, svm, online, help 
summary: Mit System Manager können NFS-Clients authentifiziert werden, um auf Daten auf der SVM zuzugreifen. 
---
= Konfigurieren Sie das NFS-Protokoll mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) lassen sich NFS-Clients für den Zugriff auf Daten der SVM authentifizieren.



== Bearbeiten Sie die NFS-Einstellungen

Mit System Manager können Sie die NFS-Einstellungen bearbeiten, z. B. NFSv3, NFSv4 und NFSv4.1. Damit werden Delegationen zu Lese- und Schreibvorgängen für NFSv4-Clients aktiviert oder deaktiviert und NFSv4-ACLs aktiviert. Sie können auch den standardmäßigen Windows-Benutzer bearbeiten.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fenster *Protokolle* auf *NFS*.
. Klicken Sie im Fenster *NFS* auf *Bearbeiten*.
. Nehmen Sie im Dialogfeld *NFS-Einstellungen bearbeiten* die erforderlichen Änderungen vor.
. Klicken Sie auf *Speichern und Schließen*.




== NFS-Fenster

Über das NFS-Fenster können Sie Ihre NFS-Einstellungen anzeigen und konfigurieren.

* *Serverstatus*
+
Zeigt den Status des NFS-Dienstes an. Der Service ist aktiviert, wenn das NFS-Protokoll auf der Storage Virtual Machine (SVM) konfiguriert ist.

+
[NOTE]
====
Wenn Sie von einem NFS-fähigen Storage-System mit Data ONTAP 8.1.x auf ONTAP 8.3 oder höher aktualisiert haben, ist der NFS-Service in ONTAP 8.3 oder höher aktiviert. Sie müssen jedoch die Unterstützung für NFSv3 oder NFSv4 aktivieren, da NFSv2 nicht mehr unterstützt wird.

====




=== Befehlsschaltflächen

* *Aktivieren*
+
Aktiviert den NFS-Service.

* *Deaktivieren*
+
Deaktiviert den NFS-Dienst.

* *Bearbeiten*
+
Öffnet das Dialogfeld NFS-Einstellungen bearbeiten, in dem Sie NFS-Einstellungen bearbeiten können.

* *Aktualisieren*
+
Aktualisiert die Informationen im Fenster.



*Verwandte Informationen*

https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS-Management"^]
