---
permalink: online-help-96-97/concept_fc_fcoe_nvme_adapters.html 
sidebar: sidebar 
keywords: system, manager, manage, fc, fcoe, nvme, adapter, online, help, edit, adapter, speed, settings 
summary: Mit System Manager können Sie FC/FCoE und NVMe Adapter verwalten. 
---
= Managen Sie FC/FCoE und NVMe Adapter mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) lassen sich FC/FCoE- und NVMe-Adapter managen.



== Bearbeiten Sie die Einstellungen für die FC/FCoE- und NVMe-Adaptergeschwindigkeit

Sie können die Einstellungen für die FC/FCoE- und NVMe-Adaptergeschwindigkeit über das Dialogfeld FC/FCoE- und NVMe-Adaptereinstellungen bearbeiten in System Manager ändern.

.Schritte
. Klicken Sie auf *Netzwerk* > *FC/FCoE und NVMe Adapter*.
. Wählen Sie den Adapter aus, den Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Stellen Sie im Dialogfeld *FC/FCoE und NVMe Adaptereinstellungen* die Adaptergeschwindigkeit auf *manuell* oder *automatisch* und klicken Sie dann auf *Speichern*.


*Verwandte Informationen*

xref:reference_network_window.adoc[Netzwerkfenster]

https://docs.netapp.com/us-en/ontap/networking/index.html["Netzwerkmanagement"]
