---
permalink: online-help-96-97/concept_service_processors.html 
sidebar: sidebar 
keywords: service, processors, monitor, manage, storage, system, manager, temperature, voltage, current, fan, speed, online, help, isolate, management, network, traffic, sp, bmc, e0m, interface, subnet, performance, routing, ip, address, edit 
summary: Mit einem Services Processor können Sie Parameter wie Temperatur, Spannung, Strom und Lüftergeschwindigkeit über System Manager überwachen und managen, indem Sie einen Services Processor verwenden. 
---
= Verwenden Sie einen Service Processor mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie einen Serviceprozessor mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher), um die Parameter Ihres Storage-Systems wie Temperatur, Spannung, Strom und Lüftergeschwindigkeit zu überwachen und zu verwalten.



== Isolierung des Managementnetzwerk-Traffic

Es handelt sich um eine Best Practice, um SP/BMC und die E0M Management-Schnittstelle in einem für Management-Datenverkehr dedizierten Subnetz zu konfigurieren. Ein laufender Datenverkehr über das Managementnetzwerk kann zu Performance-Einbußen und Routing-Problemen führen.

Der Management-Ethernet-Port an den meisten Storage Controllern (angezeigt durch ein Schraubenschlüsselsymbol auf der Rückseite des Chassis) ist mit einem internen Ethernet-Switch verbunden. Der interne Switch bietet Konnektivität zum SP/BMC sowie zur E0M Managementoberfläche, über die Sie mittels TCP/IP-Protokollen wie Telnet, SSH und SNMP auf das Storage-System zugreifen können.

Wenn Sie das Remote-Management-Gerät und E0M verwenden möchten, müssen Sie diese in demselben IP-Subnetz konfigurieren. Da es sich hierbei um Schnittstellen mit niedriger Bandbreite handelt, empfiehlt es sich, SP/BMC und E0M in einem für den Management-Datenverkehr dedizierten Subnetz zu konfigurieren.

Wenn Sie den Verwaltungsdatenverkehr nicht isolieren können oder wenn Ihr dediziertes Managementnetzwerk ungewöhnlich groß ist, sollten Sie versuchen, das Volumen des Netzwerkdatenverkehrs so gering wie möglich zu halten. Übermäßiger Ingress-Broadcast- oder Multicast-Datenverkehr kann die SP/BMC-Leistung beeinträchtigen.

[NOTE]
====
Einige Storage Controller, z. B. die AFF A800, verfügen über zwei externe Ports: Einen für BMC und die andere für E0M. Für diese Controller müssen BMC und E0M in demselben IP-Subnetz nicht konfiguriert werden.

====


== Weisen Sie Service-Prozessoren IP-Adressen zu

Mit System Manager können Sie allen Service-Prozessoren gleichzeitig IP-Adressen zuweisen und mit diesen Service-Prozessoren verschiedene Systemparameter Ihrer Speichersysteme überwachen und verwalten.

.Schritte
. Klicken Sie Auf *Konfiguration* > *Cluster* > *Konfigurationsupdates*.
. Klicken Sie im Fenster *Service Processor* auf *Globale Einstellungen*.
. Wählen Sie im Dialogfeld *Globale Einstellungen* die Quelle für die Zuweisung der IP-Adressen aus:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Weisen Sie IP-Adressen automatisch von einem DHCP-Server zu
 a| 
Wählen Sie *DHCP*.



 a| 
Weisen Sie IP-Adressen einem Subnetz zu
 a| 
Wählen Sie *Subnetz*.



 a| 
Geben Sie manuell IP-Adressen an
 a| 
Wählen Sie *Manuelle Zuweisung*.

|===
. Klicken Sie Auf *Speichern*.




== Service Processor-Einstellungen bearbeiten

Sie können Service-Prozessor-Attribute, z. B. die IP-Adresse, die Netzwerkmaske oder die Präfixlänge und die Gateway-Adresse, mit System Manager ändern. Sie können Service-Prozessoren, die keine IP-Adressen zugewiesen haben, auch IP-Adressen zuweisen.

.Über diese Aufgabe
* Sie können die Einstellungen eines Service Processor bearbeiten, dem eine IP-Adresse manuell zugewiesen wurde.
* Sie können die Einstellungen eines Service-Prozessors nicht bearbeiten, dem eine IP-Adresse über einen DHCP-Server oder über ein Subnetz zugewiesen wurde.


.Schritte
. Klicken Sie Auf *Konfiguration* > *Cluster* > *Service Processor*.
. Wählen Sie im Fenster *Service Processor* den Service Processor aus, den Sie ändern möchten, und klicken Sie dann auf *Bearbeiten*.
. Nehmen Sie im Dialogfeld *Service Processor bearbeiten* die erforderlichen Änderungen vor und klicken Sie dann auf *Speichern und Schließen*.




== Informationen über den Service Processor

Ein Service Processor ist eine systemunabhängige Ressource im Storage-System, die Ihnen dabei hilft, Parameter wie Temperatur, Spannung, Strom und Lüftergeschwindigkeit zu überwachen und zu managen.

Wenn der Service-Prozessor bei einem der Storage-Systemparameter eine anormale Bedingung erkennt, meldet der Service-Prozessor ein Ereignis, benachrichtigt ONTAP über das Problem und generiert AutoSupport-Meldungen über E-Mail oder SNMP-Traps.

Der Service-Prozessor überwacht ONTAP über einen Watchdog-Mechanismus und kann einen schnellen Failover zum Partner-Node ermöglichen. Der Service-Prozessor verfolgt zudem zahlreiche Systemereignisse und speichert die Ereignisse in einer Protokolldatei. Zu den Ereignissen gehören Boot-Status, Änderungen an der FRU (Field Replaceable Unit), von ONTAP generierte Ereignisse und der Verlauf der Benutzertransaktionen.

Der Service Processor kann sich unabhängig vom Status des Storage-Systems Remote einloggen und das Storage-System verwalten sowie Diagnosen stellen, das System herunterfahren, ein- und wieder starten oder neu. Darüber hinaus bietet der Service-Prozessor Remote-Diagnosefunktionen.

Dank der kombinierten Monitoring- und Management-Funktionen des Service Processor können Sie das Storage-System im Falle eines Problems bewerten und anschließend unmittelbar effektive Service-Aktionen durchführen.



== Service Processor-Fenster geöffnet

Über das Fenster Service Processor können Sie die Attribute der Service-Prozessoren, z. B. IP-Adresse, Netzwerkmaske (IPv4) oder Präfixlänge (IPv6) und Gateway, anzeigen und ändern oder die IP-Quelle für einen Service-Prozessor konfigurieren.



=== Befehlsschaltflächen

* *Bearbeiten*
+
Öffnet das Dialogfeld Service Processor bearbeiten, in dem Sie die IP-Adresse, Netzwerkmaske (IPv4) oder Präfixlänge (IPv6) und Gateway-Informationen eines Service Processor ändern können.

* *Globale Einstellungen*
+
Öffnet das Dialogfeld Globale Einstellungen, in dem Sie die IP-Quelle für alle Service-Prozessoren wie DHCP, Subnetz oder Handbuch konfigurieren können.

* *Aktualisieren*
+
Aktualisiert die Informationen im Fenster.





=== Liste der Service-Prozessoren

* *Knoten*
+
Gibt den Node an, auf dem sich der Service-Prozessor befindet.

* *IP-Adresse*
+
Gibt die IP-Adressen des Service-Prozessors an.

* *Status*
+
Gibt den Status des Service-Prozessors an. Dieser kann „Online“, „Offline“, „Daemon offline“, „Node offline“ oder „beeinträchtigt“ lauten. Neu gestartet oder unbekannt.

* *MAC-Adresse*
+
Gibt die MAC-Adresse des Service-Prozessors an.





=== Detailbereich

Im Bereich unterhalb der Liste des Service-Prozessors werden ausführliche Informationen zum Service-Prozessor angezeigt, einschließlich Netzwerkdetails, wie die IP-Adresse, Netzwerkmaske (IPv4) oder Präfixlänge (IPv6), Gateway, IP-Quelle, Und MAC-Adresse sowie allgemeine Details, wie die Firmware-Version und ob die automatische Aktualisierung der Firmware aktiviert ist.

*Verwandte Informationen*

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[Einrichten eines Netzwerks, wenn ein IP-Adressbereich deaktiviert ist]
