---
permalink: online-help-96-97/concept_storage_recommendations_for_creating_aggregates.html 
sidebar: sidebar 
keywords: storage, recommendations, create, aggregate, system, manager, online, help 
summary: Ab System Manager 9.4 können Sie Aggregate basierend auf Storage-Empfehlungen erstellen. Sie müssen jedoch entscheiden, ob die Erstellung von Aggregaten basierend auf Storage-Empfehlungen in Ihrer Umgebung unterstützt wird. Wenn Ihre Umgebung das Erstellen von Aggregaten auf der Grundlage von Storage-Empfehlungen nicht unterstützt, müssen Sie die RAID-Richtlinie und Festplattenkonfiguration festlegen und die Aggregate manuell erstellen. 
---
= Storage-Empfehlungen zum Erstellen von Aggregaten mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab System Manager 9.4 können Sie Aggregate basierend auf Storage-Empfehlungen erstellen. Sie müssen jedoch entscheiden, ob die Erstellung von Aggregaten basierend auf Storage-Empfehlungen in Ihrer Umgebung unterstützt wird. Wenn Ihre Umgebung das Erstellen von Aggregaten auf der Grundlage von Storage-Empfehlungen nicht unterstützt, müssen Sie die RAID-Richtlinie und Festplattenkonfiguration festlegen und die Aggregate manuell erstellen.

System Manager analysiert die verfügbaren freien Festplatten im Cluster und generiert eine Empfehlung, wie die Spare-Festplatten verwendet werden sollten, um Aggregate gemäß Best Practices zu erstellen. System Manager zeigt die Zusammenfassung der empfohlenen Aggregate einschließlich ihrer Namen und nutzbaren Größe an.

In vielen Fällen wird die Empfehlung zu Storage optimal für Ihre Umgebung umgesetzt. Wenn jedoch auf Ihrem Cluster ONTAP 9.3 oder älter ausgeführt wird oder wenn in Ihrer Umgebung die folgenden Konfigurationen enthalten sind, müssen Sie Aggregate manuell erstellen:

* Aggregate mit Array LUNs anderer Hersteller
* Virtuelle Laufwerke mit Cloud Volumes ONTAP oder ONTAP Select
* MetroCluster Konfigurationen
* SyncMirror Funktionalität
* MSATA-Festplatten
* Flash Pool-Aggregate
* Mehrere Festplattentypen oder Größen sind mit dem Node verbunden


Wenn in Ihrer Umgebung folgende Festplattenbedingungen vorhanden sind, müssen Sie außerdem die Festplattenbedingungen korrigieren, bevor Sie die Speicherempfehlung zum Erstellen von Aggregaten verwenden:

* Fehlende Festplatten
* Währungsschwankung bei den Spare-Festplatten
* Nicht zugewiesene Festplatten
* Nicht-Zeroed Spares (für ONTAP Versionen vor 9.6)
* Festplatten, die gerade durch Wartungstests getestet werden


*Verwandte Informationen*

https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["Festplatten- und Aggregatmanagement"]

xref:task_zeroing_disks.adoc[Nullsetzen von freien Festplatten]
