---
permalink: online-help-96-97/concept_lun_multiprotocol_type_guidelines.html 
sidebar: sidebar 
keywords: guidelines, lun, multiprotocol, type, operating, system, host, layout, data, minimum, maximum, size, online, help 
summary: 'Der Multiprotokoll-Typ (LUN) oder der Typ des Betriebssystems gibt das Betriebssystem des Hosts an, der auf die LUN zugreift. Es bestimmt außerdem das Layout der Daten auf der LUN sowie die minimale und maximale Größe der LUN.' 
---
= Richtlinien zur Verwendung von Multiprotocol-Typ für LUN in System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im ONTAP System Manager classic (verfügbar in ONTAP 9.7 und früher) gibt der LUN-Protokolltyp oder der Betriebssystemtyp das Betriebssystem des Hosts an, der auf die LUN zugreift. Es bestimmt außerdem das Layout der Daten auf der LUN sowie die minimale und maximale Größe der LUN.

[NOTE]
====
Nicht alle ONTAP Versionen unterstützen alle LUN-Multiprotokoll-Typen. Aktuelle Informationen finden Sie im Interoperabilitäts-Matrix-Tool.

====
In der folgenden Tabelle werden die Werte des LUN-Multi-Protokoll-Typs und die Richtlinien für die Verwendung jedes Typs beschrieben:

|===
| LUN-Multi-Protokoll-Typ | Wann verwendet werden soll 


 a| 
AIX
 a| 
Wenn Ihr Host-Betriebssystem AIX ist.



 a| 
HP-UX ERHÄLTLICH
 a| 
Wenn Ihr Host-Betriebssystem HP-UX ist.



 a| 
Hyper-V
 a| 
Wenn Sie Windows Server 2008 oder Windows Server 2012 Hyper-V verwenden und Ihre LUNs virtuelle Festplatten (VHDs) enthalten. Wenn Sie Hyper_V für Ihren LUN-Typ verwenden, sollten Sie auch Hyper_V für Ihren igroup-Betriebssystem verwenden.

[NOTE]
====
Bei RAW LUNs können Sie den Typ des Child-Betriebssystems verwenden, den der Multiprotokoll-Typ der LUN verwendet.

====


 a| 
Linux
 a| 
Wenn Ihr Host-Betriebssystem Linux ist.



 a| 
NetWare
 a| 
Wenn Ihr Hostbetriebssystem NetWare ist.



 a| 
OpenVMS
 a| 
Wenn Ihr Host-Betriebssystem OpenVMS ist.



 a| 
Solaris
 a| 
Wenn Ihr Host-Betriebssystem Solaris ist und Sie keine Solaris EFI-Etiketten verwenden.



 a| 
Solaris EFI
 a| 
Wenn Sie Solaris EFI-Etiketten verwenden.

[NOTE]
====
Die Verwendung eines anderen LUN-Multiprotocol-Typs mit Solaris EFI Etiketten kann zu Problemen bei der LUN-Ausrichtung führen.

====


 a| 
VMware
 a| 
Wenn Sie einen ESX Server verwenden und Ihre LUNs mit VMFS konfiguriert werden.

[NOTE]
====
Wenn Sie die LUNs mit RDM konfigurieren, können Sie das Gastbetriebssystem als den Multiprotokoll-Typ LUN verwenden.

====


 a| 
Windows 2003 MBR
 a| 
Wenn Ihr Host-Betriebssystem Windows Server 2003 mit der MBR-Partitionierungsmethode ist.



 a| 
Windows 2003 GPT
 a| 
Wenn Sie die GPT-Partitionierungsmethode verwenden möchten und Ihr Host sie verwenden kann. Windows Server 2003, Service Pack 1 und höher können die GPT-Partitionierungsmethode verwenden, und alle 64-Bit-Versionen von Windows unterstützen sie.



 a| 
Windows 2008 oder höher
 a| 
Wenn Ihr Host-Betriebssystem Windows Server 2008 oder höher ist, werden sowohl MBR- als auch GPT-Partitionierungsmethoden unterstützt.



 a| 
Xen
 a| 
Wenn Sie Xen verwenden und Ihre LUNs mit Linux LVM mit Dom0 konfiguriert werden.

[NOTE]
====
Bei RAW LUNs können Sie den Typ des Gast-Betriebssystems verwenden, den der LUN-Multiprotokolltyp verwendet.

====
|===
*Verwandte Informationen*

xref:task_creating_luns.adoc[LUNs werden erstellt]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilität"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148981["Solaris Host Utilities 6.1 – Installations- und Setup-Handbuch"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148983["Solaris Host Utilities 6.1 Quick Command Reference"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148982["Solaris Host Utilities 6.1 – Versionshinweise"]
