---
permalink: online-help-96-97/concept_unix.html 
sidebar: sidebar 
keywords: system, manager, unix, svm, online, help, command, button, group, tab, storage, virtual, machine 
summary: 'Mit System Manager können Sie eine Liste der lokalen UNIX-Benutzer und -Gruppen für jede Storage Virtual Machine (SVM) pflegen.' 
---
= Lokale UNIX-Benutzer und -Gruppen mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie eine Liste lokaler UNIX Benutzer und Gruppen für jede Storage Virtual Machine (SVM) pflegen.



== UNIX-Fenster

Mit dem UNIX Fenster können Sie eine Liste der lokalen UNIX-Benutzer und -Gruppen für jede Storage Virtual Machine (SVM) verwalten. Zur Authentifizierung und Namenszuordnungen können lokale UNIX-Benutzer und -Gruppen verwendet werden.



=== Registerkarte „Gruppen“

Auf der Registerkarte „Groups“ können Sie UNIX-Gruppen hinzufügen, bearbeiten oder löschen, die lokal einer SVM sind.



== Befehlsschaltflächen

* *Gruppe Hinzufügen*
+
Öffnet das Dialogfeld Gruppe hinzufügen, in dem Sie UNIX Gruppen erstellen können, die lokal bei SVMs sind. Lokale UNIX Gruppen werden mit lokalen UNIX Benutzern verwendet.

* *Bearbeiten*
+
Öffnet das Dialogfeld Gruppe bearbeiten, in dem Sie eine Gruppen-ID bearbeiten können.

* *Löschen*
+
Löscht die ausgewählte Gruppe.

* *Aktualisieren*
+
Aktualisiert die Informationen im Fenster.





=== Gruppenliste

* *Gruppenname*
+
Zeigt den Namen der Gruppe an.

* *Gruppen-ID*
+
Zeigt die ID der Gruppe an.





=== Registerkarte Benutzer

Mithilfe der Registerkarte *Users* können Sie UNIX-Benutzer hinzufügen, bearbeiten und löschen, die für SVMs lokal sind.



=== Befehlsschaltflächen

* *Benutzer Hinzufügen*
+
Öffnet das Dialogfeld Benutzer hinzufügen, in dem Sie UNIX-Benutzer erstellen können, die lokal bei SVMs vorhanden sind.

* *Bearbeiten*
+
Öffnet das Dialogfeld Benutzer bearbeiten, in dem Sie die Benutzer-ID, die UNIX-Gruppe, zu der der Benutzer gehört, und den vollständigen Namen des Benutzers bearbeiten können.

* *Löschen*
+
Löscht den ausgewählten Benutzer.

* *Aktualisieren*
+
Aktualisiert die Informationen im Fenster.





=== Benutzerliste

* *Benutzername*
+
Zeigt den Namen des Benutzers an.

* *Benutzer-ID*
+
Zeigt die ID des Benutzers an.

* * Vollständiger Name*
+
Zeigt den vollständigen Namen des Benutzers an.

* *Primäre Gruppen-ID*
+
Zeigt die ID der Gruppe an, der der Benutzer angehört.

* *Primärer Gruppenname*
+
Zeigt den Namen der Gruppe an, der der Benutzer angehört.


