---
permalink: online-help-96-97/concept_network_interfaces.html 
sidebar: sidebar 
keywords: system, manager, network, interface, create, manage, online, help, create, lif, intercluster, svm, migrate, data 
summary: Mit System Manager können Netzwerkschnittstellen erstellt und verwaltet werden. 
---
= Managen Sie die Netzwerkschnittstellen mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie Netzwerkschnittstellen erstellen und verwalten.



== Netzwerkschnittstellen erstellen

Mit System Manager können Sie eine Netzwerkschnittstelle oder eine LIF erstellen, um auf Daten von Storage Virtual Machines (SVMs) zuzugreifen. Außerdem lassen sich SVMs managen und eine Schnittstelle für Cluster-übergreifende Konnektivität bereitstellen.

.Bevor Sie beginnen
Die dem Subnetz zugeordnete Broadcast-Domäne muss über zugewiesene Ports verfügen.

.Über diese Aufgabe
* Bei der Erstellung eines LIF ist Dynamic DNS (DDNS) standardmäßig aktiviert.
+
DDNS ist jedoch deaktiviert, wenn Sie die LIF für die Cluster-Kommunikation über iSCSI-, NVMe- oder FC/FCoE-Protokolle oder nur für den Management-Zugriff konfigurieren.

* Sie können eine IP-Adresse mithilfe eines Subnetzes oder nicht mit einem Subnetz angeben.
* Sie können mit System Manager keine Netzwerkschnittstelle erstellen, wenn die Ports beeinträchtigt sind.
+
Um in diesen Fällen eine Netzwerkschnittstelle zu erstellen, müssen Sie die Befehlszeilenschnittstelle (CLI) verwenden.

* Um NVMeoF-Daten-LIF zu erstellen, muss die SVM bereits eingerichtet sein, der NVMe-Service muss bereits auf der SVM existieren und die NVMeoF-fähigen Adapter sollten verfügbar sein.
* Das NVMe-Protokoll ist nur aktiviert, wenn für die ausgewählte SVM der NVMe-Service konfiguriert ist.


.Schritte
. Klicken Sie Auf *Netzwerk* > *Netzwerkschnittstellen*.
. Klicken Sie Auf *Erstellen*.
. Geben Sie im Dialogfeld *Netzwerkschnittstelle erstellen* einen Schnittstellennamen an.
. Geben Sie eine Schnittstellenrolle an:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Zuordnen der Netzwerk-Schnittstelle zu einer Daten-LIF
 a| 
.. Wählen Sie *Dient Daten* Aus.
.. Wählen Sie die SVM für die Netzwerkschnittstelle aus.




 a| 
Verbinden Sie die Netzwerkschnittstelle mit einer Intercluster-LIF
 a| 
.. Wählen Sie *Intercluster Connectivity*.
.. Wählen Sie den IPspace für die Netzwerkschnittstelle aus.


|===
. Wählen Sie die entsprechenden Protokolle aus.
+
Die Schnittstelle verwendet die ausgewählten Protokolle für den Zugriff auf Daten der SVM.

+
[NOTE]
====
Bei Auswahl des NVMe-Protokolls werden die restlichen Protokolle deaktiviert. Bei Unterstützung von NAS-Protokollen (CIFS und NFS) bleiben die Protokolle verfügbar. Das Feld NVMe-Transport wird angezeigt, wenn Sie das NVMe-Protokoll auswählen und FC-NVMe als Transportprotokoll angezeigt wird.

====
. Wenn Sie den Managementzugriff auf der Daten-LIF aktivieren möchten, aktivieren Sie das Kontrollkästchen *Management Access aktivieren*.
+
Sie können den Managementzugriff für Cluster-übergreifende LIFs oder LIFs mit FC/FCoE- oder NVMe-Protokollen nicht aktivieren.

. Weisen Sie die IP-Adresse zu:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Geben Sie die IP-Adresse mithilfe eines Subnetzes an
 a| 
.. Wählen Sie *mit einem Subnetz* aus.
.. Wählen Sie im Dialogfeld Details hinzufügen das Subnetz aus, dem die IP-Adresse zugewiesen werden muss.
+
Für Intercluster-LIF werden nur die Subnetze angezeigt, die dem ausgewählten IPspace zugeordnet sind.

.. Wenn Sie der Schnittstelle eine bestimmte IP-Adresse zuweisen möchten, wählen Sie *eine bestimmte IP-Adresse verwenden* aus, und geben Sie dann die IP-Adresse ein.
+
Die angegebene IP-Adresse wird dem Subnetz hinzugefügt, wenn die IP-Adresse nicht bereits im Subnetz-Bereich vorhanden ist.

.. Klicken Sie auf *OK*.




 a| 
Geben Sie die IP-Adresse manuell an, ohne ein Subnetz zu verwenden
 a| 
.. Wählen Sie *ohne Subnetz*.
.. Führen Sie im Dialogfeld Details hinzufügen die folgenden Schritte aus:
+
... Geben Sie die IP-Adresse und die Netzwerkmaske oder das Präfix an.
... Optional: Geben Sie das Gateway an.
... Wenn Sie den Standardwert für das Feld Ziel nicht verwenden möchten, geben Sie einen neuen Zielwert an.
+
Wenn Sie keinen Zielwert angeben, wird das Feld Ziel basierend auf der Familie der IP-Adresse mit dem Standardwert gefüllt.



+
Wenn keine Route vorhanden ist, wird automatisch eine neue Route basierend auf dem Gateway und dem Ziel erstellt.

.. Klicken Sie auf *OK*.


|===
. Wählen Sie im Detailbereich *Port* die benötigten Ports aus.
+
** Bei Daten-LIFs werden im Bereich Port Details alle Ports aus der Broadcast-Domäne angezeigt, die dem IPspace der SVM zugeordnet sind.
** Bei Intercluster-LIFs werden im Bereich Portdetails alle Ports aus der Broadcast-Domäne angezeigt, die dem erforderlichen IPspace zugeordnet sind.
** Im Bereich Portdetails werden nur NVMe-fähige Adapter angezeigt, wenn das NVMe-Protokoll ausgewählt ist.


. *Optional:* Aktivieren Sie das Kontrollkästchen *Dynamic DNS (DDNS)*, um DDNS zu aktivieren.
. Klicken Sie Auf *Erstellen*.




== Bearbeiten Sie die Einstellungen der Netzwerkschnittstellen

Sie können mit System Manager die Netzwerkschnittstelle ändern, um den Managementzugriff für eine Daten-LIF zu ermöglichen.

.Über diese Aufgabe
* Sie können die Netzwerkeinstellungen der Cluster-LIFs, Cluster-Management-LIFs oder Node-Management-LIFs über System Manager nicht ändern.
* Sie können den Managementzugriff für eine Intercluster-LIF nicht aktivieren.


.Schritte
. Klicken Sie Auf *Netzwerk* > *Netzwerkschnittstellen*.
. Wählen Sie die Schnittstelle aus, die Sie ändern möchten, und klicken Sie dann auf *Bearbeiten*.
. Ändern Sie im Dialogfeld *Netzwerkschnittstelle bearbeiten* die Einstellungen der Netzwerkschnittstelle nach Bedarf.
. Klicken Sie auf *Speichern und Schließen*.




== Löschen der Netzwerkschnittstellen

Sie können mit System Manager eine Netzwerkschnittstelle löschen, um die IP-Adresse der Schnittstelle freizumachen und dann die IP-Adresse für einen anderen Zweck zu verwenden.

.Bevor Sie beginnen
Der Status der Netzwerkschnittstelle muss deaktiviert sein.

.Schritte
. Klicken Sie Auf *Netzwerk* > *Netzwerkschnittstellen*.
. Wählen Sie die Schnittstelle aus, die Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Aktivieren Sie das Bestätigungsfeld, und klicken Sie dann auf *Löschen*.




== Migrieren eines LIF

Sie können mit System Manager eine Daten-LIF oder eine Cluster-Management-LIF auf einen anderen Port desselben Node oder auf einem anderen Node im Cluster migrieren, wenn der Quellport fehlerhaft ist oder Wartungsarbeiten erforderlich sind.

.Bevor Sie beginnen
Der Ziel-Node und die Ports müssen betriebsbereit sein und auf dasselbe Netzwerk wie der Quellport zugreifen können.

.Über diese Aufgabe
* Wenn Sie die NIC vom Node entfernen, müssen Sie die LIFs, die auf den Ports, die der NIC angehören, zu anderen Ports im Cluster migrieren.
* Sie können iSCSI LIFs oder FC LIFs nicht migrieren.


.Schritte
. Klicken Sie Auf *Netzwerk* > *Netzwerkschnittstellen*.
. Wählen Sie die Schnittstelle aus, die Sie migrieren möchten, und klicken Sie dann auf *Migrieren*.
. Wählen Sie im Dialogfeld *Schnittstelle migrieren* den Zielport aus, zu dem Sie die LIF migrieren möchten.
. *Optional:* Aktivieren Sie das Kontrollkästchen *dauerhaft migrieren*, wenn Sie den Zielport als neuen Startport für das LIF festlegen möchten.
. Klicken Sie Auf * Migrieren*.


*Verwandte Informationen*

xref:reference_network_window.adoc[Netzwerkfenster]

xref:task_configuring_iscsi_protocol_on_svms.adoc[Konfigurieren des iSCSI-Protokolls auf SVMs]

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP-Konzepte"]

https://docs.netapp.com/us-en/ontap/networking/index.html["Netzwerkmanagement"]
