---
permalink: online-help-96-97/reference_storage_service_definitions.html 
sidebar: sidebar 
keywords: storage, service, definition, online, help, performance, factor 
summary: ONTAP umfasst vordefinierte Storage-Services, die den entsprechenden minimalen Performance-Faktoren zugeordnet sind. 
---
= Storage-Service-Definitionen für System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager Classic (verfügbar in ONTAP 9.7 und früher) umfasst vordefinierte Storage-Services, die den entsprechenden minimalen Performance-Faktoren zugeordnet sind.

Die tatsächliche Menge an Storage-Services, die in einem Cluster oder einer SVM verfügbar sind, hängt von der Storage-Art ab, aus der ein Aggregat in der SVM besteht.

Die folgende Tabelle zeigt, wie die minimalen Performance-Faktoren den vordefinierten Storage-Services zugeordnet werden:

|===
| Storage-Service | Erwartete IOPS (SLA) | IOPS-Spitzenwerte (SLO) | Minimale Volume-IOPS | Geschätzte Latenz | Werden IOPS erzwungen? 


 a| 
Wert
 a| 
128 pro TB
 a| 
512 pro TB
 a| 
75
 a| 
17 ms
 a| 
Bei AFF: Ja

Ansonsten: Nein



 a| 
Performance
 a| 
2048 pro TB
 a| 
4096 pro TB
 a| 
500
 a| 
2 ms
 a| 
Ja.



 a| 
Extrem
 a| 
6144 pro TB
 a| 
12288 pro TB
 a| 
1000
 a| 
1 ms
 a| 
Ja.

|===
Die folgende Tabelle definiert das verfügbare Storage-Service-Level für jeden Medien- oder Node-Typ:

|===
| Medien oder Node | Verfügbares Storage Service Level 


 a| 
Festplatte
 a| 
Wert



 a| 
Festplatte einer virtuellen Maschine
 a| 
Wert



 a| 
FlexArray-LUN
 a| 
Wert



 a| 
Hybrid
 a| 
Wert



 a| 
Flash mit optimierter Kapazität
 a| 
Wert



 a| 
Solid State Drive (SSD) - kein All Flash FAS System
 a| 
Wert



 a| 
Performance-optimierter Flash – SSD (AFF)
 a| 
Höchste Leistung, Mehrwert

|===