---
permalink: online-help-96-97/reference_dashboard_window.html 
sidebar: sidebar 
keywords: system, manager, dashboard, window, multiple, panel, online, help 
summary: Das Dashboard -Fenster enthält mehrere Fensterbereiche mit gesammelten Systeminformationen und der Performance. 
---
= Dashboard-Fenster für System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Dashboard-Fenster in ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) enthält mehrere Panels, die Ihnen auf einen Blick kumulative Informationen über Ihr System und seine Performance bieten.

Über das Dashboard-Fenster können Sie Informationen zu wichtigen Warnmeldungen und Benachrichtigungen, zur Effizienz und Kapazität von Aggregaten und Volumes, zu den in einem Cluster verfügbaren Nodes, den Status der Nodes in einem HA-Paar, den aktivsten Applikationen und Objekten anzeigen, Und die Performance-Kennzahlen eines Clusters oder Node.

* *Warnungen und Benachrichtigungen*
+
Zeigt alle rot angezeigten Warnmeldungen an, z. B. EMS-Notfallereignisse, Offline-Knotendetails, fehlerhafte Festplattendetails, risikoreichen Lizenzberechtigungen und Details zum Offline-Netzwerkanschluss. Zeigt alle Benachrichtigungen in Gelb an, z. B. Benachrichtigungen zur Systemzustandsüberwachung, die in den letzten 24 Stunden auf Cluster-Ebene aufgetreten sind, Lizenzberechtigungen mit mittlerem Risiko, nicht zugewiesene Festplattendetails, die Anzahl der migrierten LIFs, fehlgeschlagene Volume-Verschiebung Und Volume-Ververschiebungsoperationen, die in den letzten 24 Stunden einen administrativen Eingriff erforderlich waren.

+
Im Bereich Warnungen und Benachrichtigungen werden bis zu drei Benachrichtigungen angezeigt, über die ein Link Alle anzeigen angezeigt wird. Sie können auf den Link Alle anzeigen klicken, um weitere Informationen zu den Warnungen und Benachrichtigungen anzuzeigen.

+
Das Aktualisierungsintervall für das Feld Warnungen und Benachrichtigungen beträgt eine Minute.

* *Cluster Übersicht*
+
Zeigt die Aggregate und Volumes an, die sich der Kapazität nähern, die Storage-Effizienz eines Clusters oder Nodes und die Sicherungsdetails der wichtigsten Volumes.

+
Auf der Registerkarte Kapazität werden die oberen Online-Aggregate angezeigt, die sich der Kapazität nähern, in absteigender Reihenfolge des belegten Speicherplatzes.

+
Die Registerkarte „Kapazität“ enthält einen Link zur Anzahl der Volumes mit der höchsten verwendeten Kapazität, wenn Sie in das Feld „Volumes, die die genutzte Kapazität überschreiten“ einen gültigen Wert eingeben. Auf ihm wird außerdem die Menge der inaktiven (kalten) Daten angezeigt, die im Cluster verfügbar sind.

+
Auf der Registerkarte „Effizienz“ werden die Storage-Einsparungen für ein Cluster oder Node angezeigt. Sie können den insgesamt genutzten logischen Speicherplatz, den insgesamt genutzten physischen Speicherplatz und die Gesamteinsparungen anzeigen. Sie können ein Cluster oder einen bestimmten Node auswählen, um die Einsparungen durch die Storage-Effizienz anzuzeigen. Bei System Manager 9.5 ist der für Snapshot Kopien verwendete Speicherplatz _nicht_ in den Werten für den insgesamt genutzten logischen Speicherplatz, den insgesamt genutzten physischen Speicherplatz und die Gesamteinsparungen enthalten. Ab System Manager 9.6 wird der für Snapshot Kopien verwendete Speicherplatz jedoch in den Werten für den insgesamt genutzten logischen Speicherplatz, den insgesamt genutzten physischen Speicherplatz und die Gesamteinsparungen enthalten.

+
Das Aktualisierungsintervall für die Cluster-Übersicht beträgt 15 Minuten.

+
Auf der Registerkarte Schutz werden Informationen zu clusterweiten Volumes angezeigt, die keine definierten Schutzbeziehungen haben. Es werden nur die FlexVol Volumes und FlexGroup Volumes angezeigt, die die folgenden Kriterien erfüllen:

+
** Die Volumes sind RW-Volumes und sind online.
** Das Aggregat, das die Volumes enthält, ist online.
** Die Volumes verfügen über Sicherungsbeziehungen und sind noch nicht initialisiert.
Sie können das Fenster Volumes aufrufen, um die Volumes anzuzeigen, die über keine definierte Sicherungsbeziehung verfügen.


+
Auf der Registerkarte Sicherung werden auch die fünf wichtigsten SVMs mit der höchsten Anzahl von Volumes angezeigt, in denen keine definierten Sicherungsbeziehungen definiert sind.

* *Knoten*
+
Zeigt eine Bilddarstellung der Anzahl und Namen der im Cluster verfügbaren Nodes und des Status der in einem HA-Paar aufgeführten Nodes an. Sie sollten den Mauszeiger über die Bilddarstellung der Nodes positionieren, um den Status der Nodes in einem HA-Paar anzuzeigen.

+
Über den Link Knoten können Sie weitere Informationen zu allen Knoten anzeigen. Sie können auch auf die Bilddarstellung klicken, um das Modell der Nodes und die Anzahl der in den Nodes verfügbaren Aggregate, Storage Pools, Shelfs und Festplatten anzuzeigen. Sie können die Knoten über den Link Knoten verwalten verwalten verwalten verwalten verwalten. Sie können die Nodes in einem HA-Paar mithilfe des HA-Links managen.

+
Das Aktualisierungsintervall für das Bedienfeld Nodes beträgt 15 Minuten.

* *Anwendungen und Objekte*
+
Mit dem Bereich Applikationen und Objekte können Sie Informationen über Applikationen, Clients und Dateien in einem Cluster anzeigen.

+
Auf der Registerkarte Applikationen werden Informationen über die fünf wichtigsten Applikationen des Clusters angezeigt. Sie können die fünf wichtigsten Applikationen entweder auf Basis von IOPS und Latenz (von niedrig bis hoch oder von hoch zu niedrig) oder der Kapazität (von niedrig bis hoch oder von hoch bis niedrig) anzeigen.

+
Klicken Sie auf das entsprechende Balkendiagramm, um weitere Informationen zur Anwendung anzuzeigen. Der gesamte Speicherplatz, der genutzte Speicherplatz und der verfügbare Speicherplatz werden für die Kapazität angezeigt, die IOPS-Details werden für IOPS angezeigt und die Latenzdetails werden für die Latenz angezeigt.

+
Sie können auf *Details anzeigen* klicken, um das Anwendungsfenster der jeweiligen Anwendung zu öffnen.

+
Auf der Registerkarte Objekte werden Informationen über die fünf wichtigsten aktiven Clients und Dateien im Cluster angezeigt. Sie können die fünf wichtigsten aktiven Clients und Dateien auf Basis von IOPS oder Durchsatz anzeigen.

+
[NOTE]
====
Diese Informationen werden nur für CIFS- und NFS-Protokolle angezeigt.

====
+
Das Aktualisierungsintervall für den Bereich Anwendungen und Objekte beträgt eine Minute.

* *Leistung*
+
Zeigt durchschnittliche Performance-Metriken, Metriken zur Lese-Performance und Metriken zur Schreib-Performance des Clusters basierend auf Latenz, IOPS und Durchsatz an. Die durchschnittlichen Performance-Metriken werden standardmäßig angezeigt. Sie können auf Lesen oder Schreiben klicken, um die Metriken zur Lese-Performance bzw. Schreib-Performance anzuzeigen. Sie können die Performance-Metriken des Clusters oder eines Node anzeigen.

+
Wenn die Informationen zur Cluster-Performance nicht von ONTAP abgerufen werden können, können Sie das entsprechende Diagramm nicht anzeigen. In diesen Fällen zeigt der System Manager die spezifische Fehlermeldung an.

+
Das Aktualisierungsintervall für die Diagramme im Fenster Leistung beträgt 15 Sekunden.





== Monitoring eines Clusters mithilfe des Dashboards

Mit dem Dashboard in System Manager können Sie den Systemzustand und die Performance eines Clusters überwachen. Sie können auch mithilfe des Dashboards Hardware-Probleme und Probleme bei der Storage-Konfiguration identifizieren.

.Schritte
. Klicken Sie auf die Registerkarte *Dashboard*, um die Dashboard-Bereiche für Zustand und Leistung anzuzeigen.

