---
permalink: online-help-96-97/task_deleting_aggregates.html 
sidebar: sidebar 
keywords: delete, aggregates, system, manager, online, help, root 
summary: Wenn Sie die Daten in den Aggregaten nicht mehr benötigen, können Sie mit System Manager Aggregate löschen. Das Root-Aggregat kann jedoch nicht gelöscht werden, da es das Root-Volume enthält, das die Systemkonfigurationsinformationen enthält. 
---
= Löschen Sie Aggregate mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP System Manager classic (erhältlich in ONTAP 9.7 und früher) verwenden, um Aggregate zu löschen, wenn Sie die Daten in den Aggregaten nicht mehr benötigen. Das Root-Aggregat kann jedoch nicht gelöscht werden, da es das Root-Volume enthält, das die Systemkonfigurationsinformationen enthält.

.Bevor Sie beginnen
* Alle FlexVol Volumes und damit verbundene Storage Virtual Machines (SVMs) des Aggregats müssen gelöscht werden.
* Das Aggregat muss sich im Offline-Modus befinden.


.Schritte
. Wählen Sie eine der folgenden Methoden:
+
** Klicken Sie Auf *Anwendungen & Tiers* > *Storage Tiers*.
** Klicken Sie Auf *Storage* > *Aggregate & Disks* > *Aggregate*.


. Wählen Sie einen oder mehrere Aggregate aus, die Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Aktivieren Sie das Bestätigungsfeld, und klicken Sie dann auf *Löschen*.


*Verwandte Informationen*

xref:reference_aggregates_window.adoc[Fenster „Aggregate“]

xref:reference_storage_tiers_window.adoc[Fenster „Storage Tiers“]
