---
permalink: online-help-96-97/task_monitoring_ha_pairs.html 
sidebar: sidebar 
keywords: system, manager, ha, availability, monitor, ha, pair 
summary: Mit System Manager können Sie den Node-Status und den Interconnect-Status aller HA-Paare eines Clusters überwachen. Sie können auch überprüfen, ob Takeover oder Giveback aktiviert ist und warum Takeover oder Giveback derzeit nicht möglich sind. 
---
= Überwachen Sie HA-Paare mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie den Node-Status und den Interconnect-Status aller HA-Paare eines Clusters überwachen. Sie können auch überprüfen, ob Takeover oder Giveback aktiviert ist und warum Takeover oder Giveback derzeit nicht möglich sind.

.Schritte
. Klicken Sie Auf *Konfiguration* > *Cluster* > *Hohe Verfügbarkeit*.
. Klicken Sie im Fenster *hohe Verfügbarkeit* auf das HA-Paar-Image, um Details wie den Cluster HA-Status, den Node-Status, den Interconnect-Status und das Hardware-Modell jedes Node anzuzeigen.
+
Wenn sich die Cluster-Management-LIF oder die Daten-LIFs eines Node nicht im Home-Node befinden, wird eine Warnmeldung angezeigt, die angibt, dass der Node einige LIFs besitzt, die sich nicht im Home-Node befinden.



*Verwandte Informationen*

xref:reference_high_availability.adoc[Hochverfügbarkeit]
