---
permalink: online-help-96-97/task_setting_up_network.html 
sidebar: sidebar 
keywords: set, up, network, cluster, node, service, processor, dns, ntp, online, help 
summary: Durch das Einrichten eines Netzwerks können Sie Cluster, Nodes und Service Processor verwalten. Sie können auch DNS- und NTP-Details über das Netzwerkfenster einrichten. 
---
= Richten Sie ein Netzwerk mit System Manager - ONTAP 9.7 und früher ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie Cluster, Knoten und Serviceprozessoren verwalten, indem Sie ein Netzwerk einrichten. Sie können auch DNS- und NTP-Details über das Netzwerkfenster einrichten.

.Bevor Sie beginnen
Sie müssen das Cluster einrichten.

.Über diese Aufgabe
* Für die Cluster-Erstellung werden nur die aktiven Nodes angezeigt.
+
Sie können LIFs für diese Nodes erstellen.

* Sie können den IP-Adressbereich deaktivieren und einzelne IP-Adressen für Cluster-Management, Node-Management und Service Processor Managementnetzwerke eingeben.




== Richten Sie ein Netzwerk ein, wenn ein IP-Adressbereich aktiviert ist

Sie können ein Netzwerk einrichten, indem Sie einen IP-Adressbereich aktivieren. Im IP-Adressbereich können Sie IP-Adressen eingeben, die sich im gleichen Netzmaskenbereich oder im unterschiedlichen Netzmaskenbereich befinden.

.Schritte
. Geben Sie einen Bereich von IP-Adressen in das Feld *IP-Adressbereich* ein, und klicken Sie dann auf *Anwenden*.
+
|===
| Option | Beschreibung 


 a| 
Sie haben eine Reihe von IP-Adressen in derselben Netzmaske
 a| 
Geben Sie den IP-Adressbereich ein, und klicken Sie dann auf *Anwenden*.

IP-Adressen werden sequenziell in Cluster-Management-, Node-Management- und Service-Prozessor-Managementnetzwerke angewendet.



 a| 
Sie haben eine Reihe von IP-Adressen in verschiedenen Netzmasken
 a| 
Geben Sie jeden IP-Adressbereich in eine separate Zeile ein, und klicken Sie dann auf *Anwenden*.

Die erste IP-Adresse, die auf das Cluster-Management angewendet wird und andere IP-Adressen auch sequenziell auf das Node-Management und das Service Processor Management-Netzwerk angewendet werden.

|===
+
[NOTE]
====
Nachdem Sie den IP-Adressbereich für das Cluster-Management, das Node-Management und das Service Processor-Management eingegeben haben, dürfen Sie die IP-Adresswerte in diesen Feldern nicht manuell ändern. Sie müssen sicherstellen, dass alle IP-Adressen IPv4-Adressen sind.

====
. Geben Sie die Netzmaske und Gateway-Details ein.
. Wählen Sie den Port für die Clusterverwaltung im Feld *Port* aus.
. Wenn das Feld *Port* in der Knotenverwaltung nicht mit *E0M* ausgefüllt ist, geben Sie die Portdetails ein.
+
[NOTE]
====
Standardmäßig wird im Feld Port E0M angezeigt.

====
. Wenn Sie für die Service Processor-Verwaltung die Standardwerte überschreiben, stellen Sie sicher, dass Sie die obligatorischen Gateway-Details eingegeben haben.
. Wenn Sie das Feld *DNS Details* aktiviert haben, geben Sie die DNS-Serverdetails ein.
. Wenn Sie das Feld *NTP-Details* aktiviert haben, geben Sie die NTP-Serverdetails ein.
+
[NOTE]
====
Die Bereitstellung alternativer NTP-Serverdetails ist optional.

====
. Klicken Sie Auf *Absenden*.




=== Nächste Schritte

Geben Sie Ereignisbenachrichtigungen auf der Seite Support ein, um mit dem Cluster-Setup fortzufahren.



== Richten Sie ein Netzwerk ein, wenn ein IP-Adressbereich deaktiviert ist

Sie können ein Netzwerk einrichten, indem Sie einen IP-Adressbereich deaktivieren und einzelne IP-Adressen für das Cluster-Management, das Node-Management und die Netzwerke von Service Providern eingeben.

.Über diese Aufgabe
Wenn der Bereich *IP-Adresse* deaktiviert ist, geben Sie auf der Seite Netzwerke individuelle IP-Adressen für die Clusterverwaltung, die Knotenverwaltung und die Netzwerke der Service-Prozessoren ein.

.Schritte
. Geben Sie die Cluster-Management-IP-Adresse in das Feld * Cluster Management IP Address* ein.
. Geben Sie die Netmask-Details für das Cluster-Management ein.
. *Optional:* Geben Sie die Gateway-Details für die Cluster-Verwaltung ein.
. Wählen Sie den Port für die Clusterverwaltung im Feld *Port* aus.
. Wenn Sie Netzmaske- und Gateway-Details zur Verwaltung Ihrer Knoten angeben möchten, deaktivieren Sie das Kontrollkästchen *Netzmaske und Gateway beibehalten* der Cluster Management* und geben Sie dann die Netzmaske und Gateway-Details ein.
. Geben Sie die Knoten-Management-IP-Adressen in das Feld *Knotenverwaltung* ein.
. Wenn das Feld *Port* in der Knotenverwaltung nicht mit *E0M* ausgefüllt ist, geben Sie die Portdetails ein.
+
[NOTE]
====
Standardmäßig wird im Feld Port E0M angezeigt.

====
. Geben Sie die Service-Prozessor-Management-Netmask und Gateway-Details ein.
. Geben Sie die Service-Prozessor-IP-Management-Adressen in das Feld * Service Processor Management* ein.
. Wenn Sie das Feld *DNS Details* aktiviert haben, geben Sie die DNS-Serverdetails ein.
. Wenn Sie das Feld *NTP-Details* aktiviert haben, geben Sie die NTP-Serverdetails ein.
+
[NOTE]
====
Die Bereitstellung alternativer NTP-Serverdetails ist optional.

====
. Klicken Sie Auf *Absenden*.




=== Nächste Schritte

Geben Sie Ereignisbenachrichtigungen auf der Seite Support ein, um mit dem Cluster-Setup fortzufahren.

*Verwandte Informationen*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/What_is_a_Service_Processor_and_how_do_I_use_it%3F["Was ist ein Service Processor und wie verwende ich ihn?"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_and_troubleshoot_NTP_on_clustered_Data_ONTAP_8.2_and_later_using_CLI["Anleitung zum Konfigurieren und Beheben von Fehlern bei NTP auf Clustered Data ONTAP 8.2 und höher mithilfe von CLI"]

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 Dokumentationszentrum"]

xref:reference_network_window.adoc[Netzwerkfenster]

xref:reference_configuration_updates_window.adoc[Fenster „Konfigurationsaktualisierungen“]

xref:reference_date_time_window.adoc[Datum und Uhrzeit]

xref:reference_service_processors_window.adoc[Service Processor-Fenster geöffnet]
