---
permalink: online-help-96-97/task_aborting_vault_relationships.html 
sidebar: sidebar 
keywords: abort, snapshot, copy, transfer, online, help, system, manager 
summary: Mit System Manager kann eine gerade laufende Datenübertragung abgebrochen oder gestoppt werden. 
---
= Abbrechen des Transfers einer Snapshot Kopie mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (verfügbar in ONTAP 9.7 und früher) wird die aktuell laufende Datenübertragung abgebrochen oder gestoppt.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Beziehung aus, für die Sie die Datenübertragung beenden möchten, und klicken Sie auf *Operationen* > *Abbrechen*.
. Aktivieren Sie das Kontrollkästchen *Ja, ich möchte das Transfer* abbrechen, um den Vorgang zu bestätigen.
. *Optional:* Aktivieren Sie das Kontrollkästchen *teilweise übertragene Daten* behalten, um die Daten zu behalten, die bereits auf das Zielvolumen übertragen wurden.
. Klicken Sie Auf *Abbrechen*.


.Ergebnisse
Der Übertragungsstatus wird als „`Aborting`“ angezeigt, bis der Vorgang abgeschlossen ist und nach Abschluss des Vorgangs als „`Idle`“ angezeigt wird.

*Verwandte Informationen*

xref:reference_protection_window.adoc[Sicherungsfenster]
