---
permalink: online-help-96-97/task_assigning_disks_to_nodes.html 
sidebar: sidebar 
keywords: system, manager, assign, disk, node, online, help 
summary: Mit System Manager kann einem bestimmten Node die Eigentümerschaft einer nicht zugewiesenen Festplatte zugewiesen werden, um die Kapazität eines Aggregats oder eines Storage-Pools zu erhöhen. 
---
= Weisen Sie den Knoten mit System Manager - ONTAP 9.7 und früher Festplatten zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager classic (erhältlich in ONTAP 9.7 und älter) können Sie einem bestimmten Node Eigentumsrechte an einer nicht zugewiesenen Festplatte zuweisen, um die Kapazität eines Aggregats oder eines Storage-Pools zu erhöhen.

.Über diese Aufgabe
* Sie können Festplatten zuweisen, wenn die folgenden Bedingungen erfüllt sind:
+
** Der Containertyp der ausgewählten Festplatten muss „`nicht zugewiesen`“ sein.
** Die Festplatten müssen mit den Nodes in einem HA-Paar verbunden sein.
** Die Festplatten müssen für den Knoten sichtbar sein.


* Bei MetroCluster-Konfigurationen können Festplatten nicht mit System Manager zugewiesen werden.
+
Stattdessen müssen Sie die Befehlszeilenschnittstelle verwenden.



.Schritte
. Klicken Sie Auf *Storage* > *Aggregate & Disks* > *Disks*.
. Wählen Sie im Fenster *Disks* die Registerkarte *Inventar* aus.
. Wählen Sie die Festplatten aus, die Sie zuweisen möchten, und klicken Sie dann auf *Zuweisen*.
. Wählen Sie im Dialogfeld *Festplatten zuweisen* den Knoten aus, dem Sie die Festplatten zuweisen möchten.
. Klicken Sie Auf *Zuweisen*.

