---
permalink: online-help-96-97/task_editing_mirror_relationships.html 
sidebar: sidebar 
keywords: system, manager, edit, mirror, relationships, online, help 
summary: Mit System Manager können Sie eine gespiegelte Beziehung bearbeiten, indem Sie eine vorhandene Richtlinie auswählen oder im Cluster Zeitplan festlegen oder eine Richtlinie oder einen Zeitplan erstellen. 
---
= Verwalten Sie Spiegelbeziehungen mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP System Manager Classic (verfügbar in ONTAP 9.7 und früher) zum Managen von Spiegelbeziehungen verwenden. Sie können aktualisieren, erstellen, stilllegen, initialisieren, wiederherstellen, Löschen und Bearbeiten von Spiegelbeziehungen sowie Wiederaufnehmen stillgelegten Spiegelbeziehungen.



== Beziehungen löschen

Mit System Manager können Sie eine gespiegelte Beziehung löschen und die gespiegelte Beziehung zwischen den Quell- und Ziel-Volumes permanent beenden. Wenn eine gespiegelte Beziehung gelöscht wird, wird die Basis-Snapshot Kopie des Quell-Volume gelöscht.

.Über diese Aufgabe
Es ist eine Best Practice, die Spiegelbeziehung zu unterbrechen, bevor die Beziehung gelöscht wird.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die zu löschende Spiegelbeziehung aus und klicken Sie auf *Löschen*.
. Aktivieren Sie die Kontrollkästchen, um die Spiegelbeziehung zu löschen und die Basis-Snapshot-Kopien freizugeben, und klicken Sie dann auf *Löschen*.


.Ergebnisse
Die Beziehung wird gelöscht und die Snapshot Basis-Kopie auf dem Quell-Volume wird gelöscht.



== Beziehungen neu synchronisieren

Sie können System Manager verwenden, um eine zuvor beschädigte Spiegelbeziehung wiederherzustellen. Sie können einen Neusynchronisierung durchführen, um nach einem Ausfall, bei dem das Quell-Volume deaktiviert wurde, eine Wiederherstellung durchzuführen.

.Bevor Sie beginnen
Das Quell- und Ziel-Cluster sowie die Quell-SVM und Ziel-SVM müssen sich in Peer-Beziehungen befinden.

.Über diese Aufgabe
* Wenn Sie eine Neusynchronisierung durchführen, wird der Inhalt des gespiegelten Ziels durch den Inhalt des Quell-Volume überschrieben.
+
[NOTE]
====
** Für SnapLock-Compliance-Volumes werden alle Datenänderungen im aktiven Filesystem mit Verweis auf die allgemeine Snapshot Kopie in einer gesperrten Snapshot Kopie aufbewahrt, bis die für das aktuelle Volume festgelegte Ablaufzeit beträgt.
+
Wenn die Ablaufzeit eines Volumes in der Vergangenheit liegt oder noch nicht festgelegt wurde, sind die Snapshot Kopie und die allgemeine Snapshot Kopie für eine Dauer von 30 Tagen gesperrt. Alle Zwischen-Snapshot-Kopien der gemeinsamen Snapshot Kopie und der neuesten gesperrten Snapshot Kopie werden gelöscht.

** Bei allen anderen Volumes als SnapLock Compliance Volumes kann die Neusynchronisierung einen Verlust neuerer Daten nach der Erstellung der Basis-Snapshot Kopie nach dem Schreiben auf das Ziel-Volume verursachen.


====
* Wenn im Feld Fehler Letzter Transfer im Fenster Schutz eine Neusynchronisierung empfohlen wird, müssen Sie zuerst die Beziehung unterbrechen und dann den Neusynchronisierung durchführen.


.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Spiegelbeziehung aus, die Sie neu synchronisieren möchten.
. Klicken Sie Auf *Operationen* > *Resync*.
. Aktivieren Sie das Bestätigungsfeld und klicken Sie dann auf *Resync*.




== Setzen Sie stillgelegte Beziehungen fort

Sie können System Manager verwenden, um eine stillgelegte Spiegelbeziehung fortzusetzen. Wenn Sie die Beziehung fortsetzen, wird der normale Datentransfer zum Spiegelziel fortgesetzt und alle Spiegelaktivitäten werden neu gestartet.

.Über diese Aufgabe
Wenn Sie eine beschädigte Spiegelbeziehung von der Befehlszeilenschnittstelle (CLI) stillgelegt haben, können Sie die Beziehung zu System Manager nicht wieder aufnehmen. Sie müssen die Verbindung mit der CLI fortsetzen.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Spiegelbeziehung aus, die Sie fortsetzen möchten.
. Klicken Sie Auf *Operationen* > *Fortsetzen*.
. Aktivieren Sie das Bestätigungsfeld und klicken Sie auf *Fortsetzen*.


.Ergebnisse
Die Datenübertragung an das gespiegelte Ziel wird für die ausgewählte gespiegelte Beziehung fortgesetzt.



== Beziehungen aktualisieren

Mit System Manager können Sie eine außerplanmäßige Spiegelaktualisierung des Ziels initiieren. Möglicherweise müssen Sie ein manuelles Update durchführen, um Datenverlust aufgrund eines bevorstehenden Stromausfalls, geplanter Wartungsarbeiten oder Datenmigrationen zu vermeiden.

.Bevor Sie beginnen
Die Mirror-Beziehung muss sich in einem Snapmirrored Zustand befinden.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Spiegelbeziehung aus, für die Sie die Daten aktualisieren möchten, und klicken Sie auf *Operationen* > *Update*.
. Wählen Sie eine der folgenden Optionen:
+
** Wählen Sie *on Demand* aus, um eine inkrementelle Übertragung aus der kürzlich erstellten Snapshot Kopie zwischen den Quell- und Ziel-Volumes durchzuführen.
** Wählen Sie *Snapshot Kopie* aus und geben Sie die Snapshot Kopie an, die Sie übertragen möchten.


. *Optional:* Wählen Sie *Limit Transfer bandwidth to*, um die für Transfers verwendete Netzwerkbandbreite zu begrenzen und die maximale Übertragungsgeschwindigkeit festzulegen.
. Klicken Sie Auf *Aktualisieren*.
. Überprüfen Sie den Übertragungsstatus auf der Registerkarte *Details*.




== Beziehungen stilllegen

Mit System Manager kann ein Spiegelungszielort stillgelegt werden, um es zu stabilisieren, bevor Sie eine Snapshot Kopie erstellen. Der Quiesce-Vorgang ermöglicht den Abschluss aktiver Spiegeltransfers und deaktiviert zukünftige Transfers für die Spiegelbeziehung.

.Über diese Aufgabe
Sie können nur Spiegelbeziehungen stilllegen, die im SnapMirror-Status liegen.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Spiegelbeziehung aus, die Sie stilllegen möchten.
. Klicken Sie Auf *Operationen* > *Quiesce*.
. Aktivieren Sie das Bestätigungsfeld und klicken Sie auf *Quiesce*.




== Beziehungen initialisieren

Wenn Sie eine Mirror-Beziehung starten, müssen Sie diese Beziehung initialisieren. Das Initialisieren einer Beziehung besteht aus einem vollständigen Basistransfer der Daten vom Quell-Volume zum Ziel-Volume. Sie können mit System Manager eine Spiegelbeziehung initialisieren, wenn Sie die Beziehung während der Erstellung nicht bereits initialisiert haben.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Spiegelbeziehung aus, die Sie initialisieren möchten.
. Klicken Sie Auf *Operationen* > *Initialisieren*.
. Aktivieren Sie das Bestätigungsfeld und klicken Sie auf *Initialisieren*.
. Überprüfen Sie den Status der Spiegelbeziehung im Fenster *Schutz*.


.Ergebnisse
Eine Snapshot Kopie wird erstellt und an das Ziel übertragen. Diese Snapshot Kopie dient als Basis für nachfolgende inkrementelle Snapshot Kopien.



== Beziehungen bearbeiten

Mit System Manager können Sie eine gespiegelte Beziehung bearbeiten, indem Sie eine vorhandene Richtlinie auswählen oder im Cluster Zeitplan festlegen oder eine Richtlinie oder einen Zeitplan erstellen.

.Über diese Aufgabe
* Sie können keine gespiegelte Beziehung bearbeiten, die zwischen einem Volume in Data ONTAP 8.2.1 und einem Volume in ONTAP 8.3 oder höher erstellt wird.
* Sie können die Parameter einer vorhandenen Richtlinie oder eines vorhandenen Zeitplans nicht bearbeiten.
* Sie können den Beziehungstyp einer versionsflexiblen Spiegelbeziehung, Vault-Beziehung oder Mirror und Vault-Beziehung ändern, indem Sie den Richtlinientyp ändern.


.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Spiegelbeziehung aus, für die Sie die Richtlinie oder den Zeitplan ändern möchten, und klicken Sie dann auf *Bearbeiten*.
. Wählen Sie im Dialogfeld *Beziehung bearbeiten* eine vorhandene Richtlinie aus oder erstellen Sie eine Richtlinie:
+
|===
| Ihr Ziel ist | Gehen Sie wie folgt vor... 


 a| 
Wählen Sie eine vorhandene Richtlinie aus
 a| 
Klicken Sie auf *Durchsuchen* und wählen Sie dann eine vorhandene Richtlinie aus.



 a| 
Erstellen einer Richtlinie
 a| 
.. Klicken Sie Auf *Create Policy*.
.. Geben Sie einen Namen für die Richtlinie an.
.. Legen Sie die Priorität für geplante Transfers fest.
+
Niedrig gibt an, dass die Übertragung die geringste Priorität hat und normalerweise nach normalen Prioritätstransfers geplant ist. Standardmäßig ist die Priorität auf „Normal“ festgelegt.

.. Aktivieren Sie das Kontrollkästchen *Alle Quell-Snapshot-Kopien übertragen*, um die Regel „`all_Source_Snapshots`“ in die Spiegelrichtlinie aufzunehmen, mit der Sie alle Snapshot-Kopien vom Quell-Volume sichern können.
.. Aktivieren Sie das Kontrollkästchen *Netzwerkkomprimierung* aktivieren, um die zu übertragenden Daten zu komprimieren.
.. Klicken Sie Auf *Erstellen*.


|===
. Geben Sie einen Zeitplan für die Beziehung an:
+
|===
| Wenn... | Gehen Sie wie folgt vor... 


 a| 
Sie möchten einen vorhandenen Zeitplan zuweisen
 a| 
Wählen Sie in der Liste der Schichtpläne einen vorhandenen Zeitplan aus.



 a| 
Sie möchten einen Zeitplan erstellen
 a| 
.. Klicken Sie Auf *Zeitplan Erstellen*.
.. Geben Sie einen Namen für den Zeitplan an.
.. Wählen Sie entweder *Basic* oder *Advanced*.
+
*** Basic gibt nur den Wochentag, die Uhrzeit und das Übertragungsintervall an.
*** Advanced erstellt einen Zeitplan im cron-Stil.


.. Klicken Sie Auf *Erstellen*.




 a| 
Sie möchten keinen Zeitplan zuweisen
 a| 
Wählen Sie *Keine*.

|===
. Klicken Sie auf *OK*, um die Änderungen zu speichern.




== Mirror-Beziehungen von einer Ziel-SVM erstellen

Mit System Manager lässt sich eine Spiegelbeziehung von der Ziel-Storage Virtual Machine (SVM) erstellen und der Mirror-Beziehung eine Richtlinie und einen Zeitplan zuweisen. Die Spiegelkopie ermöglicht eine rasche Verfügbarkeit von Daten, wenn die Daten auf dem Quell-Volume beschädigt oder verloren gehen.

.Bevor Sie beginnen
* Der Quell-Cluster muss ONTAP 8.2.2 oder höher ausführen.
* Die SnapMirror Lizenz muss auf dem Quell-Cluster und dem Ziel-Cluster aktiviert sein.
+
[NOTE]
====
Bei einigen Plattformen ist es nicht erforderlich, dass die SnapMirror Lizenz für das Quell-Cluster aktiviert ist, wenn auf dem Ziel-Cluster die SnapMirror Lizenz und die DPO-Lizenz (Data Protection Optimization) aktiviert sind.

====
* Wenn Sie beim Spiegeln eines Volumes als Quelle ein SnapLock Volume auswählen, müssen die SnapMirror Lizenz und die SnapLock Lizenz auf dem Ziel-Cluster installiert sein.
* Das Quell-Cluster und das Ziel-Cluster müssen sich in einer gesunden Peer-Beziehung befinden.
* Der Ziel-SVM muss über Speicherplatz verfügen.
* Ein Quell-Volume vom Typ Read/Write (rw) muss vorhanden sein.
* Die FlexVol-Volumes müssen online sein und vom Typ „Lese/Schreib“ sein.
* Der SnapLock Aggregattyp muss vom gleichen Typ sein.
* Wenn Sie eine Verbindung von einem Cluster herstellen, auf dem ONTAP 9.2 oder früher ausgeführt wird, zu einem Remote-Cluster herstellen, auf dem die SAML-Authentifizierung (Security Assertion Markup Language) aktiviert ist, muss die passwortbasierte Authentifizierung auf dem Remote-Cluster aktiviert sein.


.Über diese Aufgabe
* System Manager unterstützt keine Kaskadenbeziehung.
+
Beispielsweise kann ein Ziel-Volume in einer Beziehung nicht das Quell-Volume in einer anderen Beziehung sein.

* Es ist nicht möglich, eine gespiegelte Beziehung zwischen einer SVM mit synchroner Quell- und einer SVM in einer MetroCluster Konfiguration zu erstellen.
* Sie können in einer MetroCluster Konfiguration eine gespiegelte Beziehung zwischen synchronen Quell-SVMs erstellen.
* Es ist möglich, eine gespiegelte Beziehung zwischen einem Volume auf einer Quell-SVM und einem Volume auf einer Datenservice-SVM zu erstellen.
* Sie können eine gespiegelte Beziehung zwischen einem Volume auf einer Datenservice-SVM und einem Datensicherungs-Volume (DP) auf einer synchronen SVM erstellen.
* Sie können eine gespiegelte Beziehung zwischen SnapLock-Volumes vom gleichen Typ nur erstellen.
+
Wenn das Quell-Volume beispielsweise ein SnapLock Enterprise Volume ist, muss das Ziel-Volume auch ein SnapLock Enterprise Volume sein. Sie müssen sicherstellen SnapLock, dass auf der Ziel-SVM Aggregate desselben Typs verfügbar sind.

* Das Ziel-Volume, das für eine Spiegelbeziehung erstellt wurde, ist kein Thin Provisioning.
* In einer Auswahl können maximal 25 Volumes geschützt werden.
* Sie können keine Spiegelbeziehung zwischen SnapLock Volumes erstellen, wenn auf dem Ziel-Cluster eine Version von ONTAP ausgeführt wird, die älter als die ONTAP Version ist, auf der das Quell-Cluster ausgeführt wird.


.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Klicken Sie im Fenster *Volume Relationships* auf *Erstellen*.
. Wählen Sie im Dialogfeld *SVM durchsuchen* eine SVM für das Ziel-Volume aus.
. Wählen Sie im Dialogfeld *Schutzbeziehung erstellen* aus der Dropdown-Liste *Beziehungstyp* die Option *Mirror* aus.
. Geben Sie den Cluster, die SVM und das Quell-Volume an.
+
Wenn auf dem angegebenen Cluster eine Version der ONTAP Software vor ONTAP 9.3 ausgeführt wird, werden nur Peering SVMs aufgelistet. Wenn im angegebenen Cluster ONTAP 9.3 oder höher ausgeführt wird, werden die Peering-SVMs und erlaubte SVMs aufgelistet.

. Geben Sie bei FlexVol Volumes ein Suffix für Volume-Namen an.
+
Das Suffix des Volume-Namens wird an die Namen des Quell-Volumes angehängt, um die Namen des Ziel-Volumes zu generieren.

. Klicken Sie auf *Durchsuchen* und ändern Sie dann die Spiegelrichtlinie.
. Wählen Sie einen Zeitplan für die Beziehung aus der Liste der vorhandenen Zeitpläne aus.
. Wählen Sie *Beziehung initialisieren*, um die Spiegelbeziehung zu initialisieren.
. Aktivieren Sie FabricPool-fähige Aggregate und wählen Sie anschließend eine entsprechende Tiering-Richtlinie aus.
. Klicken Sie Auf *Erstellen*.


.Ergebnisse
Wenn Sie ein Zielvolume erstellen möchten, wird ein Zielvolumen vom Typ _dp_ erstellt, wobei das Sprachattribut auf das Sprachattribut des Quell-Volumes eingestellt ist.

Zwischen dem Quell-Volume und dem Ziel-Volume wird eine Mirror-Beziehung erstellt. Die Basis-Snapshot-Kopie wird an das Ziel-Volume übertragen, wenn Sie sich für die Initialisierung der Beziehung entschieden haben.



== Spiegelbeziehungen neu synchronisieren

Sie können mit System Manager eine zuvor beschädigte Spiegelbeziehung wiederherstellen. Bei einer umgekehrten Neusynchronisierung werden die Funktionen des Quell-Volume und des Ziel-Volume rückgängig gemacht.

.Bevor Sie beginnen
Das Quell-Volume muss online sein.

.Über diese Aufgabe
* Sie können das Ziel-Volume verwenden, um Daten bereitzustellen, während Sie das Quell-Volume reparieren oder ersetzen, das Quell-Volume aktualisieren und die ursprüngliche Konfiguration der Systeme wiederherstellen.
* Bei einer umgekehrten Neusynchronisierung werden die Inhalte der gespiegelten Quelle durch den Inhalt des Ziel-Volume überschrieben.
+
[NOTE]
====
** Für SnapLock-Compliance-Volumes werden alle Datenänderungen im aktiven Filesystem mit Verweis auf die allgemeine Snapshot Kopie in einer gesperrten Snapshot Kopie aufbewahrt, bis die für das aktuelle Volume festgelegte Ablaufzeit beträgt.
+
Wenn die Ablaufzeit eines Volumes in der Vergangenheit liegt oder noch nicht festgelegt wurde, sind die Snapshot Kopie und die allgemeine Snapshot Kopie für eine Dauer von 30 Tagen gesperrt. Alle Zwischen-Snapshot-Kopien der gemeinsamen Snapshot Kopie und der neuesten gesperrten Snapshot Kopie werden gelöscht.

** Bei allen anderen Volumes als SnapLock Compliance Volumes kann die Neusynchronisierung einen Verlust neuerer Daten nach der Erstellung der Basis-Snapshot Kopie nach dem Schreiben auf das Quell-Volume verursachen.


====
* Bei der umgekehrten Neusynchronisierung ist die Spiegelrichtlinie der Beziehung auf DPDefault festgelegt und der Spiegelzeitplan auf Keine gesetzt.


.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Mirror-Beziehung aus, die Sie umkehren möchten.
. Klicken Sie Auf *Operationen* > *Resync Rückwärts*.
. Aktivieren Sie das Bestätigungsfeld, und klicken Sie dann auf *Resync rückwärts*.


*Verwandte Informationen*

xref:reference_protection_window.adoc[Sicherungsfenster]
