---
permalink: online-help-96-97/task_restoring_volume_vault_relationship.html 
sidebar: sidebar 
keywords: system, manager, restore, volume, vault, relationship, online, help, snapshot, copy 
summary: System Manager stellt Snapshot Kopien auf einem Quell-Volume oder auf anderen Volumes wieder her, falls die Quelldaten beschädigt sind und nicht mehr verwendbar sind. Sie können die Originaldaten durch die Snapshot Kopien im Ziel-Volume ersetzen. 
---
= Stellen Sie ein Volume in einer Vault-Beziehung mit System Manager - ONTAP 9.7 und früher wieder her
:allow-uri-read: 


[role="lead"]
Mit ONTAP System Manager Classic (verfügbar ab ONTAP 9.7) können Snapshot Kopien auf einem Quell-Volume oder auf anderen Volumes wiederhergestellt werden, sofern die Quelldaten beschädigt sind und nicht mehr verwendet werden können. Sie können die Originaldaten durch die Snapshot Kopien im Ziel-Volume ersetzen.

.Bevor Sie beginnen
* Die SnapMirror Lizenz muss sowohl auf dem Quell-Storage-System als auch auf dem Ziel-Storage-System oder auf den Nodes aktiviert werden, die das Quell-Volume und das Ziel-Volume enthalten.
* Das Quell-Cluster und das Ziel-Cluster müssen sich in einer gesunden Peer-Beziehung befinden.
* Das Quellaggregat oder ein anderes Aggregat, das Sie für die Wiederherstellung auswählen, muss ein 64-bit-Aggregat sein.
* Wenn Sie eine Verbindung von einem Cluster mit ONTAP 9.2 oder einer älteren Version zu einem Remote-Cluster herstellen, auf dem die SAML-Authentifizierung aktiviert ist, muss die passwortbasierte Authentifizierung auch auf dem Remote-Cluster aktiviert sein.


.Über diese Aufgabe
* Sie können ein Volume, das sich in einer Vault-Beziehung zwischen einer Quell-Storage Virtual Machine (SVM) und einer Ziel-SVM in einer MetroCluster Konfiguration befindet, nicht wiederherstellen.
* Sie können eine Vault-Beziehung zwischen synchronen Quell-SVMs in einer MetroCluster Konfiguration wiederherstellen.
* Sie können eine Vault-Beziehung von einem Volume auf einer Quell-SVM zu einer Standard-SVM wiederherstellen.
* Sie können eine Vault-Beziehung von einem Volume auf einer Standard-SVM auf einem DP-Volume auf einer SVM mit Sync-Source wiederherstellen.


.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Tresor-Beziehung aus, und klicken Sie dann auf *Operationen* > *Wiederherstellen*.
. Stellen Sie im Dialogfeld *Restore* die Daten in der Vault-Beziehung auf dem Quell-Volume wieder her oder wählen Sie ein anderes Volume aus:
+
|===
| Daten werden in folgenden Fall wiederhergestellt: | Tun Sie das... 


 a| 
Das Quell-Volume
 a| 
.. Wählen Sie *Quellvolumen*.
.. Fahren Sie mit Schritt 6 fort.




 a| 
Jedes andere Volume
 a| 
Wählen Sie *Other Volume* aus, und wählen Sie dann aus der Liste den Cluster und die SVM aus.

|===
. Stellen Sie die Daten auf einem neuen Volume wieder her, oder wählen Sie ein beliebiges vorhandenes Volume aus:
+
|===
| Daten werden in folgenden Fall wiederhergestellt: | Tun Sie das... 


 a| 
Ein neues Volume
 a| 
Wenn Sie den Standardnamen ändern möchten, wird im Format angezeigt `destination_SVM_name_destination_volume_name_` Stellen Sie wieder her, geben Sie einen neuen Namen an und wählen Sie dann das zugehörige Aggregat für das Volume aus.



 a| 
Einem vorhandenen Volume
 a| 
Wählen Sie die Option *Lautstärke auswählen*.

Sie müssen ein anderes Volume als das Quell-Volume auswählen, oder ein Lese-/Schreib-Volume mit einigen darin enthalten Daten und einer gemeinsamen Snapshot Kopie.

Es werden nur die Volumes mit dem gleichen Sprachattribut aufgelistet, die das Quellvolume aufweisen.

|===
. Wählen Sie entweder die neueste Snapshot Kopie oder die spezifische Snapshot Kopie aus, die Sie wiederherstellen möchten.
. Aktivieren Sie das Kontrollkästchen Bestätigung, um das Volume aus der Snapshot Kopie wiederherzustellen.
. *Optional:* Aktivieren Sie das Kontrollkästchen *Netzwerkkomprimierung aktivieren*, um die Daten zu komprimieren, die während des Wiederherstellungsvorgangs übertragen werden.
. Klicken Sie Auf *Wiederherstellen*.


*Verwandte Informationen*

xref:reference_protection_window.adoc[Sicherungsfenster]
