---
permalink: online-help-96-97/task_updating_cifs_group_policy_configuration.html 
sidebar: sidebar 
keywords: update, cifs, group, policy, configuration, online, help, enable, disable, modify, reload, set, up 
summary: 'Sie müssen die Gruppenrichtlinie aktualisieren, nachdem die Richtlinienkonfiguration über die Befehlszeilenschnittstelle (CLI) geändert wurde. Sie können das CIFS-Fenster in System Manager verwenden, um die Gruppenrichtlinie zu aktualisieren.' 
---
= Managen Sie die Konfiguration der CIFS-Gruppenrichtlinien mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das CIFS-Fenster in ONTAP System Manager classic (verfügbar in ONTAP 9.7 und früher) verwenden, um die Gruppenrichtlinie zu aktualisieren und zu verwalten.



== Aktualisieren Sie die Konfiguration der CIFS-Gruppenrichtlinien

Sie müssen die Gruppenrichtlinie aktualisieren, nachdem die Richtlinienkonfiguration über die Befehlszeilenschnittstelle (CLI) geändert wurde.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie auf die Registerkarte *Domäne*.
. Wählen Sie im Bereich *Gruppenrichtlinie* die Gruppenrichtlinienkonfiguration aus, die Sie aktualisieren möchten, und klicken Sie dann auf *Aktualisieren*.




== Aktivieren oder deaktivieren Sie die Konfiguration von CIFS-Gruppenrichtlinien

Sie können die Konfiguration der CIFS-Gruppenrichtlinien im CIFS-Fenster in System Manager aktivieren oder deaktivieren.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie auf die Registerkarte *Domäne*.
. Wählen Sie im Bereich *Gruppenrichtlinie* die Gruppenrichtlinienkonfiguration aus, die Sie aktivieren oder deaktivieren möchten, und klicken Sie dann nach Bedarf auf *Aktivieren* oder *Deaktivieren*.




== CIFS-Gruppenrichtlinie neu laden

Sie müssen eine CIFS-Gruppenrichtlinie neu laden, wenn der Status der Richtlinie geändert wird. Sie können das CIFS-Fenster in System Manager verwenden, um die Gruppenrichtlinie neu zu laden.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie auf die Registerkarte *Domäne*.
. Wählen Sie im Bereich *Gruppenrichtlinie* die Gruppenrichtlinienkonfiguration aus, die Sie neu laden möchten, und klicken Sie dann auf *Reload*.

