---
permalink: online-help-96-97/task_accessing_cluster_by_using_system_manager_by_using_browser.html 
sidebar: sidebar 
keywords: online, help, access, cluster, ontap, system, manager, graphic, interface, cli, command, line, interface 
summary: 'Wenn Sie eine grafische Schnittstelle anstelle der Befehlszeilenschnittstelle (CLI) für den Zugriff auf ein Cluster und das Verwalten verwenden möchten, können Sie dies per ONTAP System Manager ausführen. Dieser ist standardmäßig in ONTAP als Webservice enthalten und ist über einen Browser zugänglich.' 
---
= Zugriff auf ein Cluster mithilfe der Browser-basierten grafischen Oberfläche von ONTAP System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine grafische Schnittstelle anstelle der Befehlszeilenschnittstelle (CLI) für den Zugriff auf ein Cluster und das Verwalten verwenden möchten, können Sie dies per ONTAP System Manager ausführen. Dieser ist standardmäßig in ONTAP als Webservice enthalten und ist über einen Browser zugänglich.

.Bevor Sie beginnen
* Sie müssen ein Cluster-Benutzerkonto besitzen, das mit dem konfiguriert ist `admin` Rolle und der `http`, `ontapi`, und `console` Applikationstypen
* Sie müssen Cookies und Website-Daten im Browser aktiviert haben.


.Über diese Aufgabe
Sie können eine Cluster-Management-LIF oder Node-Management-LIF verwenden, um auf ONTAP System Manager zuzugreifen. Für einen unterbrechungsfreien Zugriff auf ONTAP System Manager sollten Sie eine Cluster-Management-LIF verwenden.

.Schritte
. Rufen Sie im Webbrowser die IP-Adresse der Cluster-Management-LIF auf:
+
** Wenn Sie IPv4 verwenden: `+https://cluster-mgmt-LIF+`
** Wenn Sie IPv6 verwenden: `https://[cluster-mgmt-LIF]`
Nur HTTPS wird für den Browser-Zugriff von ONTAP System Manager unterstützt.


+
Wenn das Cluster ein selbstsigniertes digitales Zertifikat verwendet, wird im Browser möglicherweise eine Warnung angezeigt, dass das Zertifikat nicht vertrauenswürdig ist. Sie können entweder das Risiko bestätigen, den Zugriff fortzusetzen, oder ein von der Zertifizierungsstelle signiertes digitales Zertifikat auf dem Cluster zur Server-Authentifizierung installieren.

. Wenn Sie über die CLI ein Zugriffbanner konfiguriert haben, lesen Sie die Meldung, die im Dialogfeld *Warnung* angezeigt wird, und wählen Sie die erforderliche Option zum Fortfahren aus.
+
Diese Option wird nicht auf Systemen unterstützt, auf denen die SAML-Authentifizierung (Security Assertion Markup Language) aktiviert ist.

+
** Wenn Sie nicht fortfahren möchten, klicken Sie auf *Abbrechen* und schließen Sie den Browser.
** Wenn Sie fortfahren möchten, klicken Sie auf *OK*, um zur Anmeldeseite des ONTAP-System-Managers zu navigieren.


. Melden Sie sich mit den Anmeldedaten des Cluster-Administrators bei ONTAP System Manager an.


*Verwandte Informationen*

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 Dokumentationszentrum"]
