---
permalink: online-help-96-97/task_changing_raid_configuration_when_creating_aggregate.html 
sidebar: sidebar 
keywords: system, manager, raid, configuration, aggregate, online, help 
summary: Beim Erstellen eines Aggregats können Sie die Standardwerte des RAID-Typs und der RAID-Gruppengrößen des Aggregats mithilfe von System Manager ändern. 
---
= Ändern Sie die RAID-Konfiguration, wenn Sie ein Aggregat mit System Manager - ONTAP 9.7 und früher erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Erstellen eines Aggregats können Sie ONTAP System Manager classic (verfügbar in ONTAP 9.7 und früher) verwenden, um die Standardwerte des RAID-Typs und der RAID-Gruppen-Größenoptionen des Aggregats zu ändern.

.Über diese Aufgabe
Wenn der Festplattentyp der Aggregat-Festplatten FSAS oder MSATA ist und die Festplattengröße mindestens 10 TB beträgt, ist RAID-TEC der einzige verfügbare RAID-Typ.

.Schritte
. Wählen Sie eine der folgenden Methoden:
+
** Klicken Sie Auf *Anwendungen & Tiers* > *Storage Tiers*.
** Klicken Sie Auf *Storage* > *Aggregate & Disks* > *Aggregate*.


. Klicken Sie im Fenster *Storage Tiers* auf *Aggregat hinzufügen*.
. Führen Sie im Dialogfeld * Aggregat erstellen* die folgenden Schritte aus:
+
.. Klicken Sie Auf *Ändern*.
.. Geben Sie im Dialogfeld *RAID-Konfiguration* ändern den RAID-Typ und die RAID-Gruppengröße an.
+
Gemeinsam genutzte Festplatten unterstützen zwei RAID-Typen: RAID DP und RAID-TEC.

+
Die empfohlene RAID-Gruppengröße beträgt 12 Festplatten bis 20 Festplatten für HDDs und 20 Festplatten bis zu 28 Festplatten für SSDs.

.. Klicken Sie Auf *Speichern*.



