---
permalink: online-help-96-97/task_aborting_mirror_relationships.html 
sidebar: sidebar 
keywords: abort, mirror, transfer, online, help, volume, replication 
summary: Sie können einen Replikationsvorgang abbrechen, bevor die Datenübertragung abgeschlossen ist. Sie können eine geplante Aktualisierung, ein manuelles Update oder eine erste Datenübertragung abbrechen. 
---
= Abbrechen Sie einen Spiegeltransfer mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) wird ein Volume-Replikationsvorgang abgebrochen, bevor die Datenübertragung abgeschlossen ist. Sie können eine geplante Aktualisierung, ein manuelles Update oder eine erste Datenübertragung abbrechen.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Beziehung aus, für die Sie die Datenübertragung beenden möchten, und klicken Sie auf *Operationen* > *Abbrechen*.
. Klicken Sie auf das Kontrollkästchen *Ja, ich möchte das Transfer* abbrechen, um den Vorgang zu bestätigen.
. Klicken Sie auf das Kontrollkästchen *teilweise übertragene Daten behalten*, um die Daten zu behalten, die bereits auf das Ziel-Volume übertragen wurden.
. Klicken Sie Auf *Abbrechen*.
+
Der Übertragungsstatus wird als „`Aborting`“ angezeigt, bis der Vorgang abgeschlossen ist und nach Abschluss des Vorgangs als „`Idle`“ angezeigt wird.



*Verwandte Informationen*

xref:reference_protection_window.adoc[Sicherungsfenster]
