---
permalink: online-help-96-97/task_setting_up_support_page.html 
sidebar: sidebar 
keywords: set, up, support, page, cluster, setup, online, help 
summary: Durch das Einrichten der Support-Seite wird das Cluster-Setup abgeschlossen. Es umfasst die Einrichtung von Ereignisbenachrichtigungen sowie die Konfiguration des System-Backups mit einem Node. 
---
= Richten Sie eine Support-Seite mit System Manager - ONTAP 9.7 und früher ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und älter) können Sie eine Support-Seite einrichten. Durch das Einrichten der Support-Seite wird das Cluster-Setup abgeschlossen. Es umfasst die Einrichtung von Ereignisbenachrichtigungen sowie die Konfiguration des System-Backups mit einem Node.

.Bevor Sie beginnen
Sie müssen das Cluster und das Netzwerk eingerichtet haben.

.Schritte
. Richten Sie die Ereignisbenachrichtigungen mithilfe des Mailhost oder SNMP-Trap-Hosts oder Syslog-Servers ein.
+
[NOTE]
====
Sie müssen mindestens ein Ereignibenachrichtigungssystem einrichten.

====
. Wenn Sie über ein Single-Node-Cluster verfügen, konfigurieren Sie eine Systemsicherung auf einem FTP-Server oder auf einem HTTP-Server.
+
[NOTE]
====
Das System-Backup ist nur für Single-Node Cluster anwendbar.

====
. Klicken Sie auf *Senden und fortfahren*.




== Nächste Schritte

Sehen Sie sich die Storage-Empfehlungen an und erstellen Sie SVMs, um das Cluster-Setup fortzusetzen.
