---
permalink: online-help-96-97/task_provisioning_basic_template.html 
sidebar: sidebar 
keywords: sap, hana, provisioning, basic, template, online, help, system, manager 
summary: Mit System Manager lassen sich grundlegende Vorlagen für SAP HANA schnell bereitstellen. 
---
= Stellen Sie mit System Manager – ONTAP 9.7 und früher eine grundlegende Vorlage bereit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) lassen sich Grundvorlagen für SAP HANA schnell bereitstellen.

.Über diese Aufgabe
Als Cluster-Administrator können Sie Applikationen bereitstellen, indem Sie eine grundlegende Vorlage konfigurieren. Das Beispiel beschreibt die Konfiguration des *SAP HANA-Servers*.

.Schritte
. Klicken Sie Auf *Anwendungen & Tiers* > *Anwendungen*
. Wählen Sie auf der Registerkarte *Basic* die Vorlage *SAP HANA Server* aus.
. Geben Sie im Abschnitt **Datenbankdetails**Folgendes an:
+
** Datenbankname
** Datenbankgröße
** Protokollgröße
** Tempdb-Größe
** Anzahl der Serverkerne
** Hinweise zu HA-Controllern


. Klicken Sie Auf *Storage Bereitstellen*


.Ergebnisse
Die Anwendung SAP HANA Server wird bereitgestellt.

*Verwandte Informationen*

link:reference_application_provisioning_settings.html["Feldbeschreibungen finden Sie unter Einstellungen für die Anwendungsbereitstellung"]
