---
permalink: online-help-96-97/task_stopping_svms.html 
sidebar: sidebar 
keywords: stop, svm, online, help, system, manager, storage, virtual, machine 
summary: 'Mit System Manager kann eine Storage Virtual Machine (SVM) angehalten werden, falls Probleme mit der SVM behoben, die SVM gelöscht oder der Datenzugriff von der SVM unterbrochen werden sollen.' 
---
= Stoppen Sie SVMs mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können Sie eine Storage Virtual Machine (SVM) anhalten, wenn Probleme mit der SVM behoben, die SVM gelöscht oder der Datenzugriff von der SVM unterbrochen werden sollen.

.Bevor Sie beginnen
Alle mit der SVM verbundenen Clients müssen getrennt werden.

[NOTE]
====
Wenn alle Clients beim Beenden der SVM verbunden sind, kann es zu Datenverlusten kommen.

====
.Über diese Aufgabe
* SVMs können während des Storage-Failovers (SFO) nicht angehalten werden.
* Wenn Sie die SVM beenden, kann sich ein SVM-Administrator nicht bei der SVM anmelden.


.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, die Sie anhalten möchten, und klicken Sie dann auf *Stopp*.


.Ergebnisse
Die SVM stellt keine Daten mehr für die Clients bereit.
