---
permalink: online-help-96-97/task_deleting_flexgroup_volumes.html 
sidebar: sidebar 
keywords: delete, flexgroup, volumes, online, help, system, manager 
summary: Ein FlexGroup Volume kann mit System Manager gelöscht werden, wenn Sie das FlexGroup Volume nicht mehr benötigen. 
---
= Löschen Sie FlexGroup Volumes mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP System Manager Classic (verfügbar ab ONTAP 9.7) verwenden, um ein FlexGroup-Volume zu löschen, wenn Sie das FlexGroup-Volume nicht mehr benötigen.

.Bevor Sie beginnen
* Der Verbindungspfad des FlexGroup-Volumes muss abgehängt werden.
* Das FlexGroup Volume muss sich offline befinden.


.Über diese Aufgabe
System Manager unterstützt nicht das zusammengehörige Management von FlexGroup Volumes.

.Schritte
. Klicken Sie Auf *Storage* > *Volumes*.
. Wählen Sie im Dropdown-Menü im Feld *SVM* die Option *Alle SVMs* aus.
. Wählen Sie das FlexGroup-Volume aus, das Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Aktivieren Sie das Bestätigungsfeld, und klicken Sie dann auf *OK*.


*Verwandte Informationen*

xref:reference_volumes_window.adoc[Fenster Volumes]
