---
permalink: online-help-96-97/task_restoring_volume_mirror_vault_relationship.html 
sidebar: sidebar 
keywords: restore, volume, mirror, vault, relationship, online, help, snapshot, copy, system, manager 
summary: System Manager stellt Snapshot Kopien auf einem Quell-Volume oder auf anderen Volumes wieder her, falls die Quelldaten beschädigt sind und nicht mehr verwendbar sind. Sie können die Originaldaten durch die Snapshot Kopien im Ziel-Volume ersetzen. 
---
= Stellen Sie ein Volume in einer Spiegelungs- und Vault-Beziehung mit System Manager - ONTAP 9.7 und früher wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (verfügbar ab ONTAP 9.7) können Snapshot Kopien auf einem Quell-Volume oder auf anderen Volumes wiederhergestellt werden, sofern die Quelldaten beschädigt sind und nicht mehr verwendet werden können. Sie können die Originaldaten durch die Snapshot Kopien im Ziel-Volume ersetzen.

.Bevor Sie beginnen
* Die SnapMirror Lizenz und die SnapVault Lizenz müssen auf dem Quell-Cluster und auf dem Ziel-Cluster oder auf den Nodes, die das Quell-Volume und das Ziel-Volume enthalten, aktiviert sein.
* Das Quell-Cluster und das Ziel-Cluster müssen sich in einer gesunden Peer-Beziehung befinden.
* Das Quellaggregat oder ein anderes Aggregat, das Sie für die Wiederherstellung auswählen, muss ein 64-bit-Aggregat sein.
* Wenn Sie eine Verbindung von einem Cluster mit ONTAP 9.2 oder einer älteren Version zu einem Remote-Cluster herstellen, auf dem die SAML-Authentifizierung aktiviert ist, muss die passwortbasierte Authentifizierung auch auf dem Remote-Cluster aktiviert sein.


.Über diese Aufgabe
* Sie können ein Volume, das sich in einer Spiegelungs- und Vault-Beziehung zwischen einer Quell-Storage Virtual Machine (SVM) und einer Ziel-SVM in einer MetroCluster Konfiguration befindet, nicht wiederherstellen.
* Sie können für die folgenden Konfigurationen eine Mirror- und Vault-Beziehung wiederherstellen:
+
** Zwischen synchronen SVMs in einer MetroCluster Konfiguration
** Von einem Volume auf einer synchronen Quell-SVM zu einer Standard-SVM
** Von einem Volume auf einer Standard-SVM zu einem DP-Volume auf einer synchronen SVM




.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Mirror- und Vault-Beziehung aus, die Sie wiederherstellen möchten, und klicken Sie dann auf *Operationen* > *Restore*.
. Stellen Sie im Dialogfeld *Wiederherstellen* die Daten in der Beziehung auf dem Quell-Volume wieder her oder wählen Sie ein anderes Volume aus:
+
|===
| Daten werden in folgenden Fall wiederhergestellt: | Tun Sie das... 


 a| 
Das Quell-Volume
 a| 
.. Wählen Sie *Quellvolumen*.
.. link:#step6["Fahren Sie mit Schritt 6 fort"].




 a| 
Jedes andere Volume
 a| 
Wählen Sie *Other Volume* aus, und wählen Sie dann den Cluster und die SVM aus.

|===
. Wiederherstellen der Daten auf einem neuen Volume oder einem vorhandenen Volume:
+
|===
| Daten werden in folgenden Fall wiederhergestellt: | Tun Sie das... 


 a| 
Ein neues Volume
 a| 
Wenn Sie den Standardnamen ändern möchten, der im Format „`destination_SVM_Name_Destination_Volume_Name_restore`“ angezeigt wird, geben Sie einen neuen Namen an, und wählen Sie dann das Aggregat aus, das für das Volume enthalten ist.



 a| 
Einem vorhandenen Volume
 a| 
Wählen Sie die Option *Lautstärke auswählen*.

Sie müssen ein anderes Volume als das Quell-Volume auswählen, oder ein Lese-/Schreib-Volume mit einigen darin enthalten Daten und einer gemeinsamen Snapshot Kopie.

Es werden nur die Volumes mit dem gleichen Sprachattribut aufgelistet, die das Quellvolume aufweisen.

|===
. Wählen Sie entweder die neueste Snapshot Kopie oder die spezifische Snapshot Kopie aus, die Sie wiederherstellen möchten.
. [[step6]]Aktivieren Sie das Kontrollkästchen zur Bestätigung, um das Volume aus der Snapshot Kopie wiederherzustellen.
. *Optional:* Aktivieren Sie das Kontrollkästchen *Netzwerkkomprimierung aktivieren*, um die Daten zu komprimieren, die während des Wiederherstellungsvorgangs übertragen werden.
. Klicken Sie Auf *Wiederherstellen*.

