---
permalink: online-help-96-97/task_hiding_snapshot_copy_directory.html 
sidebar: sidebar 
keywords: hide, snapshot, copy, directory, system, manager, online, help 
summary: 'Mithilfe von System Manager kann das Snapshot Kopie-Verzeichnis (.Snapshot) ausgeblendet werden, damit das Verzeichnis der Snapshot Kopie nicht sichtbar ist, wenn Sie Ihre Volume-Verzeichnisse anzeigen. Standardmäßig ist das Snapshot-Verzeichnis sichtbar.' 
---
= Verbergen Sie das Verzeichnis der Snapshot Kopie mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (verfügbar ab ONTAP 9.7) können Sie das Verzeichnis der Snapshot Kopien ausblenden  `.snapshot`) Damit das Verzeichnis der Snapshot-Kopie nicht sichtbar ist, wenn Sie Ihre Volume-Verzeichnisse einsehen. Standardmäßig wird der verwendet `.snapshot` Verzeichnis wird angezeigt.

.Schritte
. Klicken Sie Auf *Storage* > *Volumes*.
. Wählen Sie im Dropdown-Menü im Feld *SVM* die Option *Alle SVMs* aus.
. Wählen Sie das Volume aus, für das Sie das Verzeichnis der Snapshot-Kopie ausblenden möchten.
. Klicken Sie Auf *Weitere Aktionen* > *Snapshots Verwalten* > *Konfigurationseinstellungen*.
. Stellen Sie sicher, dass die Option *Snapshot-Verzeichnis (.Snapshot) sichtbar* nicht ausgewählt ist, und klicken Sie dann auf *OK*.


*Verwandte Informationen*

xref:reference_volumes_window.adoc[Fenster Volumes]
