---
permalink: online-help-96-97/task_aborting_mirror_vault_relationships.html 
sidebar: sidebar 
keywords: abort, mirror, vault, relationship, online, help, data, transfer 
summary: Sie können einen Replikationsvorgang abbrechen, wenn Sie die Datenübertragung anhalten möchten. Sie können eine geplante Aktualisierung, ein manuelles Update oder eine erste Datenübertragung abbrechen. 
---
= Abbrechen von Mirror- und Vault-Beziehungen mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (verfügbar in ONTAP 9.7 und früher) wird ein Volume-Replikationsvorgang abgebrochen, wenn Sie die Datenübertragung anhalten möchten. Sie können eine geplante Aktualisierung, ein manuelles Update oder eine erste Datenübertragung abbrechen.

.Schritte
. Klicken Sie Auf *Schutz* > *Volume Relationships*.
. Wählen Sie die Mirror- und Vault-Beziehung aus, für die Sie die Datenübertragung beenden möchten, und klicken Sie dann auf *Operationen* > *Abbrechen*.
. Aktivieren Sie das Kontrollkästchen *Ja, ich möchte das Transfer* abbrechen, um den Vorgang zu bestätigen.
. *Optional:* Aktivieren Sie das Kontrollkästchen *teilweise übertragene Daten* behalten, um die Daten zu behalten, die bereits auf das Zielvolumen übertragen wurden.
. Klicken Sie Auf *Abbrechen*.


.Ergebnisse
Der Übertragungsstatus wird als „`Aborting`“ angezeigt, bis der Vorgang abgeschlossen ist und nach Abschluss des Vorgangs als „`Idle`“ angezeigt wird.
