---
permalink: online-help-96-97/task_creating_svms.html 
sidebar: sidebar 
keywords: create, svm, system, manager, cluster, online, help 
summary: 'Mit System Manager können vollständig konfigurierte Storage Virtual Machines (SVMs) erstellt werden, mit denen Daten sofort bereitgestellt werden können. Ein Cluster kann eine oder mehrere SVMs enthalten.' 
---
= SVMs erstellen mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und früher) können vollständig konfigurierte Storage Virtual Machines (SVMs) erstellt werden, mit denen Daten sofort bereitgestellt werden können. Ein Cluster kann eine oder mehrere SVMs enthalten.

.Bevor Sie beginnen
* Der Cluster muss mindestens ein nicht-Root-Aggregat im Online-Status haben.
* Das Aggregat muss über ausreichend Platz für das SVM-Root-Volume verfügen.
* Sie müssen die Zeit über das Cluster hinweg synchronisiert haben, indem Sie NTP konfigurieren und aktivieren, um Fehler bei der CIFS-Erstellung und -Authentifizierung zu verhindern.
* Die Protokolle, die Sie für die SVM konfigurieren möchten, müssen lizenziert sein.
* Sie müssen das CIFS-Protokoll konfiguriert haben, damit Secure DDNS funktioniert.


.Über diese Aufgabe
* Während Sie SVMs erstellen, führen Sie folgende Aufgaben durch:
+
** Erstellung und vollständige Konfiguration von SVMs
** Konfigurieren Sie den Volume-Typ, der auf SVMs zulässig ist.
** Erstellen und Konfigurieren von SVMs mit minimaler Netzwerkkonfiguration
** Delegieren der Administration an SVM-Administratoren


* Um den Namen der SVM zu benennen, können Sie alphanumerische Zeichen sowie die folgenden Sonderzeichen verwenden: „`“.`" (period), "`-`" (Bindestrich) und "`_`" (Unterstrich).
+
Der SVM-Name sollte mit einem Alphabet oder „`_`“ (Unterstrich) beginnen und darf nicht mehr als 47 Zeichen enthalten.

+
[NOTE]
====
Sie sollten eindeutige, vollständig qualifizierte Domänennamen (FQDNs) für den SVM-Namen wie z. B. vs0.example.com verwenden.

====
* Sie können SnapMirror Beziehungen nur zwischen Volumes einrichten, die dieselben Spracheinstellungen haben.
+
Die Sprache der SVM bestimmt den Zeichensatz, mit dem Dateinamen und Daten aller NAS-Volumes in der SVM angezeigt werden.

* Sie können kein SnapLock Aggregat als Root-Aggregat der SVMs verwenden.


.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Klicken Sie Auf *Erstellen*.
. Geben Sie im Fenster *Storage Virtual Machine (SVM) Setup* die folgenden Details an:
+
** SVM-Name
** Der SVM zugewiesener IP-Speicherplatz
** Zulässiger Volume-Typ
** Zulässige Protokolle
** SVM Sprache
** Sicherheitstyp des Root-Volumes
** Root-Aggregat
+
Die Standardeinstellung für eine SVM ist C.UTF-8.

+
Standardmäßig wird das Aggregat mit dem maximalen freien Speicherplatz als Container für das Root-Volume der SVM ausgewählt. Basierend auf den ausgewählten Protokollen werden der Standardsicherheitsstil und das Root-Aggregat ausgewählt.

+
Der Sicherheitsstil lautet NTFS, wenn Sie CIFS-Protokoll oder eine Kombination aus CIFS-Protokoll mit den anderen Protokollen auswählen. Der Sicherheitsstil lautet UNIX, wenn Sie sich für NFS, iSCSI, NVMe oder FC/FCoE oder eine Kombination dieser Protokolle entscheiden.

+
[NOTE]
====
NVMe ermöglicht die Kombination der Protokolle nicht.

====


+
In einer MetroCluster-Konfiguration werden nur die Aggregate angezeigt, die im Cluster enthalten sind.

. Geben Sie die DNS-Domänennamen und die IP-Adressen des Namensservers an, um die DNS-Dienste zu konfigurieren.
+
Die Standardwerte werden aus den vorhandenen SVM-Konfigurationen ausgewählt.

. *Optional:* beim Konfigurieren einer Daten-LIF für den Zugriff auf Daten mithilfe eines Protokolls geben Sie den Zielalias, Subnetze und die Anzahl der LIFs pro Node an.
+
Sie können das Kontrollkästchen *LIFs-Konfiguration überprüfen oder ändern (Erweiterte Einstellungen)* aktivieren, um die Anzahl der Portsätze in der logischen Schnittstelle zu ändern.

+
Sie können die Details des Portset in einem bestimmten Knoten bearbeiten, indem Sie den Knoten aus der Liste Knoten im Detailbereich auswählen.

. *Optional:* Host-seitige Applikationen wie SnapDrive und SnapManager für den SVM-Administrator durch Bereitstellung der SVM-Anmeldedaten aktivieren.
. *Optional:* für andere Protokolle als NVMe, erstellen Sie eine neue LIF für SVM-Management, indem Sie auf *Erstellen einer neuen LIF für SVM-Management* klicken und dann die Portsätze und die IP-Adresse mit oder ohne Subnetz für die neue Management-LIF angeben.
+
Für CIFS- und NFS-Protokolle haben Daten-LIFs standardmäßig Zugriff auf das Management. Sie müssen nur bei Bedarf eine neue Management-LIF erstellen. Für iSCSI und FC ist eine SVM-Management-LIF erforderlich, da Datenprotokolle und Managementprotokolle nicht dieselbe LIF teilen können.

. *Optional:* für das NVMe-Protokoll ab ONTAP 9.5 konfigurieren Sie mindestens eine logische Schnittstelle für jeden Node auf der zweiten Seite des SVM Setup-Assistenten: *NVMe-Protokoll konfigurieren*
+
Sie müssen mindestens eine LIF für jeden Node im HA-Paar konfigurieren. Sie können auch zwei LIFs pro Node angeben. Klicken Sie auf das Symbol für die Einstellungen, um zwischen einer oder zwei LIFs-Konfigurationen umzuschalten.

. Klicken Sie Auf *Absenden & Fortfahren*.
+
Die SVM wird mit der angegebenen Konfiguration erstellt.



.Ergebnisse
Die von Ihnen erstellte SVM wird automatisch gestartet. Der Name des Root-Volumes wird automatisch generiert als `SVM name_root`. Standardmäßig wird der verwendet `vsadmin` Benutzerkonto wird erstellt und befindet sich im Status gesperrt.



== Nächste Schritte

Sie müssen mindestens ein Protokoll auf der SVM konfigurieren, um den Datenzugriff zu ermöglichen.
