---
permalink: online-help-96-97/task_creating_snaplock_volumes.html 
sidebar: sidebar 
keywords: create, snaplock, volume, online, help, system, manager 
summary: Mit System Manager können Sie ein SnapLock Compliance Volume oder ein SnapLock Enterprise Volume erstellen. Bei der Erstellung eines Volumes können Sie auch die Aufbewahrungszeiten festlegen und entscheiden, ob DER WORM-Status für Daten im Volume automatisiert werden soll. 
---
= Erstellen Sie SnapLock Volumes mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und älter) können Sie ein SnapLock-Compliance-Volume oder ein SnapLock Enterprise Volume erstellen. Bei der Erstellung eines Volumes können Sie auch die Aufbewahrungszeiten festlegen und entscheiden, ob DER WORM-Status für Daten im Volume automatisiert werden soll.

.Bevor Sie beginnen
* Die SnapLock Lizenz muss installiert worden sein.
* Das SnapLock Aggregat muss online sein.
* Zum Erstellen eines verschlüsselten Volumes müssen Sie die Volume-Verschlüsselungslizenz mit System Manager installiert haben, und Sie müssen „`Key-Manager Setup`“ über die Befehlszeilenschnittstelle (CLI) aktiviert haben.
+
Sie müssen Ihren Webbrowser aktualisieren, nachdem Sie „`key-Manager Setup`“ aktiviert haben.



.Über diese Aufgabe
* Sie können ein komplettes SnapLock Enterprise Volume oder eine Datei in einem SnapLock Enterprise Volume löschen. Es ist jedoch nicht möglich, nur die Daten einer Datei in einem SnapLock Enterprise Volume zu löschen.
* Ein SnapLock-Konformitätsvolume kann nicht gelöscht werden, wenn Daten auf das Volume gesetzt sind.
* Sie können ein Volume nicht in Cloud Volumes ONTAP verschlüsseln.
* Wenn auf dem Quell-Volume die Verschlüsselung aktiviert ist und auf dem Ziel-Cluster eine ältere Version der ONTAP Software als ONTAP 9.3 ausgeführt wird, wird die Verschlüsselung auf dem Ziel-Volume standardmäßig deaktiviert.


.Schritte
. Klicken Sie Auf *Storage* > *Volumes*.
. Klicken Sie auf *Erstellen* > *FlexVol erstellen*.
. Durchsuchen Sie die Storage Virtual Machine (SVM), auf der Sie das Volume erstellen möchten, und wählen Sie sie aus.
. Geben Sie im Dialogfeld *Volume erstellen* einen neuen Namen an, wenn Sie den Standardnamen des Volumes ändern möchten.
+
Sie können den Namen eines SnapLock-Konformitätsvolume nicht ändern, nachdem Sie das Volume erstellt haben.

. Wählen Sie das Container-Aggregat für das Volume aus.
+
Sie müssen ein SnapLock Compliance-Aggregat oder ein SnapLock Enterprise Aggregat auswählen, um ein SnapLock Volume zu erstellen. Das Volume übernimmt den SnapLock-Typ aus dem Aggregat, und der SnapLock-Typ kann nach dem Erstellen des Volume nicht mehr geändert werden. Daher müssen Sie das richtige Aggregat auswählen.

. Aktivieren Sie das Kontrollkästchen *Volume Encryption*, um die Verschlüsselung für das Volume zu aktivieren.
+
Diese Option steht nur zur Verfügung, wenn Sie die Lizenz für Volume Encryption aktiviert haben und wenn die entsprechende Plattform Verschlüsselung unterstützt.

. Wählen Sie den Speichertyp aus, für den Sie dieses Volume erstellen.
+
Wenn Sie ein SnapMirror Ziel-Volume erstellen, müssen Sie *Data Protection* auswählen. Sie erhalten schreibgeschützten Zugriff auf dieses Volume.

. Geben Sie die Größe des Volumes und den Prozentsatz der Gesamtgröße des Volumes an, die Sie für Snapshot Kopien reservieren möchten.
+
Der für Snapshot-Kopien reservierte Standardspeicherplatz beträgt null Prozent für SAN-Volumes und VMware Volumes. Bei NAS-Volumes beträgt der Standardwert 5 Prozent.

. *Optional:* Wählen Sie *Thin Provisioning*, um Thin Provisioning für das Volume zu aktivieren.
+
Bei aktiviertem Thin Provisioning wird dem Volume von dem Aggregat nur dann Speicherplatz zugewiesen, wenn Daten auf das Volume geschrieben werden.

. *Optional:* Machen Sie die erforderlichen Änderungen auf der Registerkarte *Storage Efficiency*, um die Deduplizierung auf dem Volume zu aktivieren.
+
System Manager verwendet den standardmäßigen Deduplizierungszeitplan. Falls die angegebene Volume-Größe die für eine laufende Deduplizierung erforderliche Obergrenze überschreitet, wird das Volume erstellt und die Deduplizierung wird nicht aktiviert.

. Wählen Sie die Registerkarte *SnapLock* aus, und führen Sie dann die folgenden Schritte aus:
+
.. *Optional:* Geben Sie den automatischen Verschiebungszeitraum an.
+
Die Datei im Volume bleibt für den von Ihnen angegebenen Zeitraum unverändert, bevor die Datei in DEN WORM-Status versetzt wird. Um Dateien manuell in DEN WORM-Status zu setzen, müssen Sie *nicht angegeben* als Autocommit-Einstellung auswählen.

+
Die Werte müssen im Bereich von 5 Minuten bis 10 Jahren liegen.

.. Geben Sie den minimalen Aufbewahrungszeitraum und den maximalen Aufbewahrungszeitraum an.
+
Die Werte müssen im Bereich von 1 Tag bis 70 Jahre liegen oder unbegrenzt sein.

.. Wählen Sie den Standardaufbewahrungszeitraum aus.
+
Die standardmäßige Aufbewahrungsfrist muss innerhalb des angegebenen Mindestaufbewahrungszeitraums und der maximalen Aufbewahrungsdauer liegen.



. *Optional:* Aktivieren Sie auf der Registerkarte *Quality of Service* das Kontrollkästchen *Storage Quality of Service* managen, um Storage QoS für das FlexVol Volume zu aktivieren, um die Workload Performance zu managen.
. Erstellung einer Storage-QoS-Richtliniengruppe oder Auswahl einer vorhandenen Richtliniengruppe zur Steuerung der I/O-Performance (Input/Output) des FlexVol Volumes
+
|===
| Ihr Ziel ist | Tun Sie das... 


 a| 
Erstellen einer Storage-QoS-Richtliniengruppe
 a| 
.. Wählen Sie *Neue Richtliniengruppe*.
.. Geben Sie den Namen der Richtliniengruppe an.
.. Geben Sie die minimale Durchsatzbegrenzung an.
+
*** In System Manager 9.5 können Sie die Durchsatzbegrenzung nur auf Performance-basierten All Flash-optimierten Systemen festlegen. In System Manager 9.6 können Sie darüber hinaus das Mindestdurchsatz-Limit für ONTAP Select Premium-Systeme festlegen.
*** Sie können das Mindestdurchsatz für Volumes nicht auf einem FabricPool-fähigen Aggregat festlegen.
*** Wenn Sie den Mindestdurchsatzwert nicht angeben oder der Mindestdurchsatzwert auf 0 gesetzt ist, wird „`Keine`“ automatisch als Wert angezeigt.
+
Bei diesem Wert wird die Groß-/Kleinschreibung beachtet.



.. Geben Sie das maximale Durchsatzlimit an, um sicherzustellen, dass die Workload der Objekte in der Richtliniengruppe das angegebene Durchsatzlimit nicht überschreitet.
+
*** Die minimale Durchsatzbegrenzung und die maximale Durchsatzbegrenzung müssen vom selben Einheitstyp sein.
*** Wenn Sie das minimale Durchsatzlimit nicht angeben, können Sie die maximale Durchsatzbegrenzung für IOPS, B/s, KB/s, MB/s usw. festlegen.
*** Wenn Sie den maximalen Durchsatzwert nicht angeben, wird „`Unlimited`“ automatisch als Wert angezeigt.
+
Bei diesem Wert wird die Groß-/Kleinschreibung beachtet. Die angegebene Einheit hat keinen Einfluss auf den maximalen Durchsatz.







 a| 
Wählen Sie eine vorhandene Richtliniengruppe aus
 a| 
.. Wählen Sie *vorhandene Richtliniengruppe* aus, und klicken Sie dann auf *Auswählen*, um eine vorhandene Richtliniengruppe im Dialogfeld Richtliniengruppe auswählen auszuwählen.
.. Geben Sie die minimale Durchsatzbegrenzung an.
+
*** In System Manager 9.5 können Sie die Durchsatzbegrenzung nur auf Performance-basierten All Flash-optimierten Systemen festlegen. In System Manager 9.6 können Sie darüber hinaus das Mindestdurchsatz-Limit für ONTAP Select Premium-Systeme festlegen.
*** Sie können das Mindestdurchsatz für Volumes nicht auf einem FabricPool-fähigen Aggregat festlegen.
*** Wenn Sie den Mindestdurchsatzwert nicht angeben oder der Mindestdurchsatzwert auf 0 gesetzt ist, wird „`Keine`“ automatisch als Wert angezeigt.
+
Bei diesem Wert wird die Groß-/Kleinschreibung beachtet.



.. Geben Sie das maximale Durchsatzlimit an, um sicherzustellen, dass die Workload der Objekte in der Richtliniengruppe das angegebene Durchsatzlimit nicht überschreitet.
+
*** Die minimale Durchsatzbegrenzung und die maximale Durchsatzbegrenzung müssen vom selben Einheitstyp sein.
*** Wenn Sie das minimale Durchsatzlimit nicht angeben, können Sie die maximale Durchsatzbegrenzung für IOPS, B/s, KB/s, MB/s usw. festlegen.
*** Wenn Sie den maximalen Durchsatzwert nicht angeben, wird „`Unlimited`“ automatisch als Wert angezeigt.
+
Bei diesem Wert wird die Groß-/Kleinschreibung beachtet. Die angegebene Einheit hat keinen Einfluss auf den maximalen Durchsatz.



+
Wenn die Richtliniengruppe mehr als einem Objekt zugewiesen ist, wird der maximale Durchsatz, den Sie angeben, von den Objekten gemeinsam genutzt.



|===
. Aktivieren Sie * Lautstärkeschutz* auf der Registerkarte *Schutz*, um das Volumen zu schützen:
. Wählen Sie auf der Registerkarte *Schutz* den Typ *Replikation* aus:
+
|===
| Wenn Sie den Replikationstyp ausgewählt haben als... | Tun Sie das... 


 a| 
Asynchron
 a| 
.. *Optional:* Wenn Sie den Replikationstyp und den Beziehungstyp nicht kennen, klicken Sie auf *Hilfe Auswählen*, legen Sie die Werte fest und klicken Sie dann auf *Anwenden*.
.. Wählen Sie den Beziehungstyp aus.
+
Der Beziehungstyp kann gespiegelt, Vault, auch gespiegelt und Vault sein.

.. Wählen Sie ein Cluster und eine SVM für das Ziel-Volume aus.
+
Wenn auf dem ausgewählten Cluster eine Version der ONTAP Software vor ONTAP 9.3 ausgeführt wird, werden nur Peering SVMs aufgelistet. Wenn auf dem ausgewählten Cluster ONTAP 9.3 oder höher ausgeführt wird, werden die Peering SVMs und zulässige SVMs aufgelistet.

.. Ändern Sie das Suffix des Volume-Namens, falls erforderlich.




 a| 
Synchron
 a| 
.. *Optional:* Wenn Sie den Replikationstyp und den Beziehungstyp nicht kennen, klicken Sie auf *Hilfe Auswählen*, legen Sie die Werte fest und klicken Sie dann auf *Anwenden*.
.. Wählen Sie die Synchronisierungsrichtlinie aus.
+
Die Synchronisierungsrichtlinie kann StrictSync oder Sync lauten.

.. Wählen Sie ein Cluster und eine SVM für das Ziel-Volume aus.
+
Wenn auf dem ausgewählten Cluster eine Version der ONTAP Software vor ONTAP 9.3 ausgeführt wird, werden nur Peering SVMs aufgelistet. Wenn auf dem ausgewählten Cluster ONTAP 9.3 oder höher ausgeführt wird, werden die Peering SVMs und zulässige SVMs aufgelistet.

.. Ändern Sie das Suffix des Volume-Namens, falls erforderlich.


|===
. Klicken Sie Auf *Erstellen*.
. Überprüfen Sie, ob das erstellte Volume in der Liste der Volumes im Fenster *Volume* enthalten ist.


.Ergebnisse
Das Volume wird mit Unix-Stil Sicherheit und UNIX 700 „`read write execute`“ Berechtigungen für den Eigentümer erstellt.
