---
permalink: online-help-96-97/task_editing_luns.html 
sidebar: sidebar 
keywords: edit, lun, properties, online, help, system, manager 
summary: Sie können im Dialogfeld LUN Properties in System Manager den Namen, die Beschreibung, die Größe, die Einstellung der Speicherplatzreservierung oder die zugeordneten Initiator-Hosts einer LUN ändern. 
---
= Bearbeiten Sie LUNs mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können im Dialogfeld LUN-Eigenschaften in ONTAP System Manager Classic (verfügbar in ONTAP 9.7 und früher) den Namen, die Beschreibung, die Größe, die Einstellung für Speicherplatzreservierung oder die zugeordneten Initiator-Hosts einer LUN ändern.

.Über diese Aufgabe
Wenn Sie die Größe einer LUN ändern, müssen Sie die für den Host-Typ und die Anwendung, die die LUN verwendet, empfohlenen Schritte auf der Host-Seite ausführen.

.Schritte
. Klicken Sie auf *Storage* > *LUNs*.
. Wählen Sie auf der Registerkarte *LUN Management* die LUN aus der Liste der LUNs aus, die Sie bearbeiten möchten, und klicken Sie auf *Bearbeiten*.
. Nehmen Sie die erforderlichen Änderungen vor.
. Klicken Sie auf *Speichern und Schließen*.


*Verwandte Informationen*

xref:reference_luns_window.adoc[LUNs-Fenster]
