---
permalink: online-help-96-97/task_editing_initiators.html 
sidebar: sidebar 
keywords: edit, initiator, online, help, group, dialog, system, manager 
summary: Sie können im Dialogfeld Initiatorgruppe bearbeiten in System Manager den Namen eines bereits vorhandenen Initiators in einer Initiatorgruppe ändern. 
---
= Bearbeiten Sie Initiatoren mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Dialogfeld *Initiatorgruppe bearbeiten* in ONTAP System Manager classic (verfügbar in ONTAP 9.7 und früher) können Sie den Namen eines bestehenden Initiators in einer Initiatorgruppe ändern.

.Schritte
. Klicken Sie auf *Storage* > *LUNs*.
. Wählen Sie auf der Registerkarte *Initiatorgruppen* die Initiatorgruppe aus, der der Initiator angehört, und klicken Sie dann auf *Bearbeiten*.
. Klicken Sie im Dialogfeld *Initiatorgruppe bearbeiten* auf *Initiatoren*.
. Wählen Sie den Initiator aus, den Sie bearbeiten möchten, und klicken Sie auf *Bearbeiten*.
. Ändern Sie den Namen und klicken Sie auf *OK*.
. Klicken Sie auf *Speichern und Schließen*.


*Verwandte Informationen*

xref:reference_luns_window.adoc[LUNs-Fenster]
