---
permalink: online-help-96-97/task_editing_initiator_groups.html 
sidebar: sidebar 
keywords: edit, initiator, group, system, manager, online, help, port, set, dialog, box 
summary: Sie können im Dialogfeld Initiatorgruppe bearbeiten in System Manager den Namen einer vorhandenen Initiatorgruppe und ihr Betriebssystem ändern. Sie können Initiatoren zu der Initiatorgruppe hinzufügen oder sie entfernen. Sie können auch den der Initiatorgruppe zugeordneten Portsatz ändern. 
---
= Bearbeiten Sie Initiatorgruppen mit System Manager - ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Dialogfeld *Initiatorgruppe bearbeiten* in ONTAP System Manager classic (verfügbar in ONTAP 9.7 und früher) können Sie den Namen einer bestehenden Initiatorgruppe und deren Betriebssystem ändern. Sie können Initiatoren zu der Initiatorgruppe hinzufügen oder sie entfernen. Sie können auch den der Initiatorgruppe zugeordneten Portsatz ändern.

.Schritte
. Klicken Sie auf *Storage* > *LUNs*.
. Wählen Sie auf der Registerkarte *Initiatorgruppen* die Initiatorgruppe aus, die Sie ändern möchten, und klicken Sie dann auf *Bearbeiten*.
. Nehmen Sie die erforderlichen Änderungen vor.
. Klicken Sie auf *Speichern und Schließen*.
. Überprüfen Sie die Änderungen, die Sie an der Initiatorgruppe auf der Registerkarte *Initiatorgruppen* vorgenommen haben.


*Verwandte Informationen*

xref:reference_luns_window.adoc[LUNs-Fenster]
