---
permalink: online-help-96-97/task_creating_qos_policy_groups.html 
sidebar: sidebar 
keywords: online, help, create, qos, policy, groups, system, manager, quality, service 
summary: 'Mit System Manager können Richtliniengruppen (Quality of Service, QoS) für Storage erstellt werden, um den Durchsatz von Workloads zu begrenzen und die Workload-Performance zu überwachen.' 
---
= Managen Sie QoS-Richtliniengruppen mit System Manager – ONTAP 9.7 und früher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager Classic (erhältlich in ONTAP 9.7 und älter) können Storage-QoS-Richtliniengruppen (Quality of Service) erstellt werden, um den Durchsatz von Workloads zu begrenzen und die Workload-Performance zu überwachen.



== Erstellen von QoS-Richtliniengruppen

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *QoS Policy Groups*.
. Klicken Sie im Fenster *QoS Policy Groups* auf *Erstellen*.
. Geben Sie im Dialogfeld *Richtliniengruppe erstellen* einen Gruppennamen für die Richtlinie an.
. Geben Sie die minimale Durchsatzbegrenzung an.
+
** In System Manager 9.5 können Sie die Durchsatzbegrenzung nur auf Performance-basierten All Flash-optimierten Systemen festlegen. In System Manager 9.6 können Sie darüber hinaus das Mindestdurchsatz-Limit für ONTAP Select Premium-Systeme festlegen.
** Sie können das Mindestdurchsatz für Volumes nicht auf einem FabricPool-fähigen Aggregat festlegen.
** Wenn Sie den Mindestdurchsatzwert nicht angeben oder der Mindestdurchsatzwert auf 0 gesetzt ist, wird „`Keine`“ automatisch als Wert angezeigt.
+
Bei diesem Wert wird die Groß-/Kleinschreibung beachtet.



. Geben Sie die maximale Durchsatzbegrenzung an.
+
** Die minimale Durchsatzbegrenzung und die maximale Durchsatzbegrenzung müssen vom selben Einheitstyp sein.
** Wenn Sie das minimale Durchsatzlimit nicht angeben, können Sie die maximale Durchsatzbegrenzung in IOPS und B/s, KB/s, MB/s usw. festlegen.
** Wenn Sie die maximale Durchsatzbegrenzung nicht angeben, wird „`Unlimited`“ automatisch als Wert angezeigt.
+
Bei diesem Wert wird die Groß-/Kleinschreibung beachtet. Die angegebene Einheit hat keinen Einfluss auf den maximalen Durchsatz.



. Klicken Sie auf *OK*.




== QoS-Richtliniengruppen löschen

Mit dem ONTAP System Manager classic (erhältlich in ONTAP 9.7 und älter) können Sie eine nicht mehr benötigte Richtliniengruppe für Storage-Servicequalität (QoS) löschen.

.Bevor Sie beginnen
Sie müssen alle Speicherobjekte aufheben, die der Richtliniengruppe zugewiesen sind.

.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *QoS Policy Groups*.
. Wählen Sie im Fenster *QoS Policy Groups* die Richtliniengruppe aus, die Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Klicken Sie im Bestätigungsdialogfeld auf *Löschen*.




== QoS-Richtliniengruppen bearbeiten

Sie können im Dialogfeld Richtliniengruppe bearbeiten in ONTAP System Manager classic (verfügbar in ONTAP 9.7 und früher) den Namen und den maximalen Durchsatz einer vorhandenen Richtliniengruppe für die Storage-Servicequalität (QoS) ändern.

.Über diese Aufgabe
* In System Manager 9.5 können Sie die Durchsatzbegrenzung nur auf Performance-basierten All Flash-optimierten Systemen festlegen. In System Manager 9.6 können Sie darüber hinaus das Mindestdurchsatz-Limit für ONTAP Select Premium-Systeme festlegen.
* Sie können das Mindestdurchsatz für Volumes nicht auf einem FabricPool-fähigen Aggregat festlegen.


.Schritte
. Klicken Sie auf *Storage* > *SVMs*.
. Wählen Sie die SVM aus, und klicken Sie dann auf *SVM Settings*.
. Klicken Sie im Fensterbereich *Richtlinien* auf *QoS Policy Groups*.
. Wählen Sie die QoS-Richtliniengruppe aus, die Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
+
** Die minimale Durchsatzbegrenzung und die maximale Durchsatzbegrenzung müssen vom selben Einheitstyp sein.
** Wenn Sie das minimale Durchsatzlimit nicht angeben, können Sie die maximale Durchsatzbegrenzung in IOPS und B/s, KB/s, MB/s usw. festlegen.
** Wenn Sie nicht die maximale Durchsatzbegrenzung angeben, wird der Wert auf unbegrenzt gesetzt, und die angegebene Einheit hat keinen Einfluss auf den maximalen Durchsatz.


. Bearbeiten Sie im Dialogfeld *Richtliniengruppe bearbeiten* die Details der QoS-Richtliniengruppe und klicken Sie dann auf *Speichern*.

