---
permalink: nfs-config-esxi/task_mounting_datastores_on_hosts.html 
sidebar: sidebar 
keywords: mount, datastore, host, access, storage, provision, automatic, add, vmware, environment, mount datastores on hosts 
summary: Durch das Mounten eines Datastore kann ein Host auf den Speicher zugreifen. Wenn Datastores von bereitgestellt werden, werden sie automatisch auf den Host oder das Cluster eingebunden. Möglicherweise müssen Sie einen Datastore auf einem Host mounten, nachdem Sie den Host zu Ihrer VMware Umgebung hinzugefügt haben. 
---
= Mounten Sie Datenspeicher auf Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Mounten eines Datastore kann ein Host auf den Speicher zugreifen. Wenn Datastores von bereitgestellt werden, werden sie automatisch auf den Host oder das Cluster eingebunden. Möglicherweise müssen Sie einen Datastore auf einem Host mounten, nachdem Sie den Host zu Ihrer VMware Umgebung hinzugefügt haben.

.Schritte
. Klicken Sie auf der Seite vSphere Web Client *Home* auf *Hosts und Cluster*:
. Erweitern Sie im Navigationsbereich das Rechenzentrum, das den Host enthält:
. Klicken Sie mit der rechten Maustaste auf den Host und wählen Sie dann *NetApp VSC* > *Mount Datastores* aus.
. Wählen Sie die Datenspeicher aus, die Sie mounten möchten, und klicken Sie dann auf *OK*.


*Verwandte Informationen*

https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html["Virtual Storage Console, VASA Provider und Storage Replication Adapter für die VMware vSphere Administration für Version 9.6"]
