---
permalink: fc-config-esxi/task_updating_hba_firmware.html 
sidebar: sidebar 
keywords: fc, host, bus, adapter, hba, esx, support, driver, firmware, bio, update, update the hba driver firmware and bios 
summary: Wenn auf den FC-Host-Bus-Adaptern im ESX-Host keine unterstützten Treiber, Firmware- und BIOS-Versionen ausgeführt werden, müssen Sie diese aktualisieren. 
---
= Aktualisieren Sie den HBA-Treiber, die Firmware und das BIOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die FC-Host Bus Adapter (HBAs) im ESX-Host nicht unterstützte Treiber, Firmware und BIOS-Versionen ausführen, müssen Sie sie aktualisieren.

.Bevor Sie beginnen
Sie müssen die unterstützten Treiber-, Firmware- und BIOS-Versionen für Ihre Konfiguration über die identifiziert haben https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"].

.Über diese Aufgabe
Die HBA-Anbieter stellen Treiber, Firmware, BIOS und HBA-Utilitys bereit.

.Schritte
. Führen Sie die installierten HBA-Treiber, Firmware und BIOS-Versionen unter Verwendung der ESXi Host-Konsolenbefehle für Ihre ESXi-Version auf.
. Laden Sie den neuen Treiber, die Firmware und das BIOS nach Bedarf auf der Support-Website des HBA-Anbieters herunter und installieren Sie es.
+
Installationsanweisungen und alle erforderlichen Installationsprogramme stehen Ihnen beim Download zur Verfügung.


