---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, linux, server, configuration, red hat enterprise linux 
summary: Sie können den FC-Service schnell auf einer Storage Virtual Machine einrichten, eine LUN bereitstellen und die LUN über einen FC-Host Bus Adapter auf einem Red hat Enterprise Linux Server zur Verfügung stellen. 
---
= FC-Konfiguration für Red hat Enterprise Linux – Übersicht
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den FC-Service schnell auf einer Storage Virtual Machine (SVM) einrichten, eine LUN bereitstellen und die LUN über einen FC-Host Bus Adapter (HBA) auf einem Red hat Enterprise Linux Server zur Verfügung stellen, wobei die klassische Schnittstelle des ONTAP System Manager (ONTAP 9.7 und früher) verwendet wird.

Gehen Sie folgendermaßen vor, um den FC-Service für eine SVM einzurichten, wenn:

* Auf dem Host wird eine unterstützte Version von Red hat Enterprise Linux 6.4 oder höher ausgeführt.
* Sie verwenden herkömmliche FC HBAs und Switches.
+

NOTE: Fibre Channel over Ethernet (FCoE) wird hier nicht behandelt.

* Auf jedem Node im Cluster sind mindestens zwei FC-Ziel-Ports verfügbar.
Integrierte FC- und UTA2-Ports (auch als „`CNA`“ bezeichnet) und einige Adapter können konfiguriert werden. Das Konfigurieren dieser Ports erfolgt in der ONTAP Befehlszeilenschnittstelle (CLI) und wird in diesem Verfahren nicht behandelt.
* Sie konfigurieren nicht das Booten von FC SAN.


Wenn diese Annahmen für Ihre Situation nicht richtig sind, sollten Sie die folgenden Ressourcen sehen:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN-Administration"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["San-Konfiguration"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Installation Von Linux Unified Host Utilities 7.1"^]




== Weitere Möglichkeiten dies in ONTAP zu tun

|===


| So führen Sie diese Aufgaben durch: | Siehe... 


| Der neu gestaltete System Manager (verfügbar ab ONTAP 9.7) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_linux.html["Bereitstellen von SAN-Storage für Linux Server"^] 


| Die ONTAP Befehlszeilenschnittstelle (CLI) | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["LUN-Setup-Workflow mit der CLI"^] 
|===