---
permalink: fc-config-rhel/task_deciding_where_to_provision_volume.html 
sidebar: sidebar 
keywords: provision, volume, contain, lun, exist, storage, virtual, machine, svm, create, fc, exist, decide where to provision the volume 
summary: Bevor Sie ein Volume bereitstellen, das die LUNs enthält, müssen Sie entscheiden, ob Sie das Volume zu einer vorhandenen Storage Virtual Machine hinzufügen oder eine neue SVM für das Volume erstellen möchten. Darüber hinaus müssen Sie möglicherweise auch FC auf einer vorhandenen SVM konfigurieren. 
---
= Legen Sie fest, wo das Volume bereitgestellt werden soll
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ein Volume bereitstellen, das die LUNs enthält, müssen Sie entscheiden, ob Sie das Volume zu einer vorhandenen Storage Virtual Machine (SVM) hinzufügen oder eine neue SVM für das Volume erstellen möchten. Darüber hinaus müssen Sie möglicherweise auch FC auf einer vorhandenen SVM konfigurieren.

.Über diese Aufgabe
Wenn eine vorhandene SVM bereits mit den erforderlichen Protokollen konfiguriert ist und über LIFs verfügt, auf die über den Host zugegriffen werden kann, wird die Nutzung der vorhandenen SVM vereinfacht.

Sie können eine neue SVM erstellen, wodurch Daten oder eine Administration von anderen Benutzern des Storage-Clusters getrennt werden. Ein Vorteil besteht darin, dass separate SVMs nur zur Trennung verschiedener Protokolle genutzt werden können.



== Verfahren

* Wenn Sie Volumes auf einer SVM bereitstellen möchten, die bereits für FC konfiguriert ist, müssen Sie überprüfen, ob der FC-Service ausgeführt wird, und dann eine LUN auf der SVM erstellen.
+
link:task_verifying_that_fc_service_is_running_on_existing_svm.html["Überprüfung, ob der FC-Service auf einer vorhandenen SVM ausgeführt wird"]

+
link:task_creating_lun_its_containing_volume.html["Erstellen einer LUN"]

* Wenn Sie Volumes auf einer vorhandenen SVM bereitstellen möchten, für die FC aktiviert, aber nicht konfiguriert ist, konfigurieren Sie iSCSI auf der vorhandenen SVM.
+
link:task_configuring_iscsi_fc_creating_lun_on_existing_svm.html["Konfigurieren von FC auf einer vorhandenen SVM"]

+
Dies ist der Fall, wenn Sie dieses Verfahren nicht zur Erstellung der SVM bei der Konfiguration eines anderen Protokolls befolgt haben.

* Wenn Sie Volumes auf einer neuen SVM bereitstellen möchten, erstellen Sie die SVM.
+
link:task_creating_svm.html["Erstellen einer neuen SVM"]


