---
permalink: fc-config-rhel/task_configuring_logical_volumes_on_multipath_devices_creating_file_system.html 
sidebar: sidebar 
keywords: linux, host, access, scsi, device, lun, partition, file, system, multipath, device, underly, scsi, lofical, create, file, system, configure, configure logical volumes on multipath devices and creating a file system 
summary: 'Wenn der Linux-Host zum ersten Mal auf ein neues SCSI-Gerät (LUN) zugreift, gibt es keine Partition oder kein Dateisystem. Wenn Sie ein partitionierte Multipath-Gerät verwenden möchten, müssen Sie zuerst die zugrunde liegenden SCSI-Geräte partitionieren. Es könnte auch sinnvoll sein, logische Volumes auf Multipath-Geräten zu erstellen und optional ein Dateisystem zu erstellen.' 
---
= Konfigurieren Sie logische Volumes auf Multipath-Geräten und erstellen Sie ein Filesystem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der Linux-Host zum ersten Mal auf ein neues SCSI-Gerät (LUN) zugreift, gibt es keine Partition oder kein Dateisystem. Wenn Sie ein partitionierte Multipath-Gerät verwenden möchten, müssen Sie zuerst die zugrunde liegenden SCSI-Geräte partitionieren. Es könnte auch sinnvoll sein, logische Volumes auf Multipath-Geräten zu erstellen und optional ein Dateisystem zu erstellen.

.Bevor Sie beginnen
SCSI-Geräte und entsprechende Multipath-Geräte müssen vom Linux-Host erkannt worden sein.

.Über diese Aufgabe
Mindestens DM-Multipath sollte auf den SCSI-Geräten konfiguriert werden. Alle Konfigurationen, die über DM-Multipath hinausgehen, sind optional. Die folgenden Schritte sind allgemeine Richtlinien, wenn Sie zusätzliche Konfigurationen durchführen möchten, wie z. B. Partitionierung, Konfiguration von logischen Volumes auf Multipath-Geräten und Erstellung eines Dateisystems. Weitere Informationen zu Linux-Befehlen finden Sie in der Dokumentation zu Red hat Enterprise Linux und den man-Pages.

.Schritte
. Um ein partitionierte Multipath-Gerät zu verwenden, partitionieren Sie zuerst die zugrunde liegenden SCSI-Geräte mithilfe des `fdisk` Oder `parted` Utility:
. Erstellen Sie die entsprechenden Multipath-Partitionen mit `kpartx` Utility:
. Erstellen Sie logische Volumes auf entsprechenden Multipath-Geräten mithilfe von LVM-Befehlen (Logical Volume Manager).
. Erstellen Sie mithilfe des ein Dateisystem, z. B. Ext4 oder XFS, auf logischen Volumes oder Multipath-Geräten `mkfs` Utility:

