---
permalink: expansion/task_generating_autosupport_message_about_completing_expansion.html 
sidebar: sidebar 
keywords: expand, cluster, autosupport, indicate, expansion, process, complete, message, communicate, internal, external, support, staff, complete, troubleshoot, generate, generate an autosupport, message about completing expansion 
summary: Nachdem Sie ein Cluster erweitert haben, sollten Sie eine AutoSupport Meldung senden, um anzugeben, dass die Erweiterung abgeschlossen ist. 
---
= Generieren Sie eine AutoSupport-Meldung über den Abschluss der Erweiterung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie ein Cluster erweitert haben, sollten Sie eine AutoSupport Meldung senden, um anzugeben, dass die Erweiterung abgeschlossen ist. Diese Nachricht teilt internen und externen Support-Mitarbeitern mit, dass die Erweiterung abgeschlossen ist und als Zeitstempel für jegliche spätere Fehlerbehebung fungiert.

.Bevor Sie beginnen
AutoSupport muss eingerichtet sein.

.Schritte
. Senden Sie für jeden Node im Cluster eine AutoSupport Meldung mithilfe von `system node autosupport invoke` Befehl.
+
Sie müssen einmal die Meldung für jeden Node im Cluster ausgeben, einschließlich der neu hinzugefügten Nodes.

+
Wenn Sie einem 2-Node-Cluster zwei Nodes hinzugefügt haben, müssen Sie die Meldung viermal senden.

+
[listing]
----
cluster1::> system node autosupport invoke -node * -message "cluster expansion complete" -type all
The AutoSupport was successfully invoked on node "cluster1-1". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
The AutoSupport was successfully invoked on node "cluster1-2". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
The AutoSupport was successfully invoked on node "cluster1-3". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
The AutoSupport was successfully invoked on node "cluster1-4". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
4 entries were acted on.
----

