---
permalink: expansion/task_backing_up_cluster_configuration.html 
sidebar: sidebar 
keywords: expand, cluster, advance, privilege, backup, file, configuration, information, back up the cluster configuration 
summary: Bevor Sie ein Cluster erweitern, sollten Sie zum Erstellen einer Sicherungsdatei die erweiterten Berechtigungen verwenden, um die Cluster-Konfigurationsinformationen zu speichern und optional die Node-Konfigurationen zu speichern. 
---
= Sichern der Cluster-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ein Cluster erweitern, sollten Sie zum Erstellen einer Sicherungsdatei die erweiterten Berechtigungen verwenden, um die Cluster-Konfigurationsinformationen zu speichern und optional die Node-Konfigurationen zu speichern.

.Schritte
. Stellen Sie die Berechtigungsebene mithilfe der auf Erweiterungssatz ein `set -privilege advanced` Befehl.
. Erstellen Sie mit dem eine Backup-Datei der Cluster-Konfiguration `system configuration backup create` Befehl mit dem `-backup-type cluster` Parameter.
+
[listing]
----
cluster1::*> system configuration backup create -node cluster1-1 -backup-name clusterbeforeexpansion.7z -backup-type cluster
[Job 5573] Job is queued: Cluster Backup OnDemand Job.
----
. Erstellen Sie mit dem eine Sicherungsdatei der Konfiguration jedes Node `system configuration backup create` Befehl mit dem `-backup-type node` Parameter für jeden Node.
. Stellen Sie die Berechtigungsebene mit zurück `set -privilege admin` Befehl.

