---
permalink: volume-restore-snapvault/task_verifying_restore_operation.html 
sidebar: sidebar 
keywords: perform, restore, operation, snapvault, backup, destination, volume, verify, source cluster, verify the restore operation 
summary: Nachdem Sie den Wiederherstellungsvorgang vom SnapVault Backup-Ziel-Volume durchgeführt haben, müssen Sie den Status des Wiederherstellungsvorgangs im Quell-Cluster überprüfen. 
---
= Überprüfen Sie den Wiederherstellungsvorgang
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie den Wiederherstellungsvorgang vom SnapVault Backup-Ziel-Volume durchgeführt haben, müssen Sie den Status des Wiederherstellungsvorgangs im Quell-Cluster überprüfen.

.Über diese Aufgabe
Sie müssen diese Aufgabe aus dem Cluster *source* ausführen.

.Schritte
. Navigieren Sie zum Fenster *Volumes*.
. Wählen Sie in der Liste Volumes das Quell-Volume aus und führen Sie abhängig von Ihrer ONTAP-Version eine der folgenden Aktionen durch:
+
** Ab ONTAP 9.3: Doppelklicken Sie auf das Quell-Volume, um die Details anzuzeigen, und klicken Sie dann auf *PROTECTION*, um das Ziel-Volume in der SnapMirror-Beziehung und den Namen der SVM zu identifizieren, die das Volume enthält.
** ONTAP 9.2 oder früher: Klicken Sie auf die Registerkarte *Data Protection* bottom, um das Ziel-Volume in der SnapMirror Beziehung und den Namen der SVM zu identifizieren, die das Volume enthält.
Das Feld Typ wird angezeigt `Restore` Vorübergehend. Nach Abschluss des Wiederherstellungsvorgangs wird das Feld angezeigt `Vault`.
+
Sie sollten Probleme in den SnapVault Beziehungen beheben. Die Fehlerbehebungsschritte für SnapMirror Beziehungen gelten auch für SnapVault Beziehungen.

+
http://www.netapp.com/us/media/tr-4015.pdf["Technischer Bericht 4015: SnapMirror Configuration and Best Practices for ONTAP 9.1, 9.2"^]




